### ISSUE TITLE
[Feature Request]: Mushroom Edibility Prediction

### ISSUE THREAD

**Issue by deca109** [manikumarreddyu/AgroTech-AI#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Number of deaths per year due to eating poisonous mushrooms is estimated to be about 100 
 worldwide. Developing a machine learning model that predicts whether a mushroom is edible or not, depending on it's physical features and environment is crucial to eradicate such deaths and educating the farming and foraging communities.

### Use Case

**- Enhanced Safety for Foragers and Farmers:** Farmers and foragers could receive real-time alerts or recommendations on whether mushrooms found or grown are safe to consume.

**- Data-Driven Harvesting Decisions:** Farmers cultivating edible mushrooms could use this model to ensure only safe, edible varieties are harvested. 

**- Market Demand and Profitability:** In the same way that the crop yield and market demand analysis can inform what crops to grow for profitability, this platform could also forecast market demand for specific edible mushrooms, helping farmers decide which safe, high-demand mushrooms to cultivate. This could be coupled with price prediction tools that anticipate which varieties may yield the highest profits.

**- Environmental Monitoring and Yield Optimization:** The platform could integrate environmental data, such as humidity and soil quality, to optimize mushroom growing conditions, increasing yield for edible species while minimizing the risk of poisonous ones contaminating the crop. B

- Education and Awareness: By using the predictive model, the platform could also serve as an educational tool for mushroom enthusiasts, providing them with guidance on identifying and safely consuming mushrooms. 

### Benefits

**- Increased Consumer Confidence:** For communities reliant on foraging or consuming mushrooms, especially in rural areas, this feature can build trust by providing a reliable way to determine edibility, thereby lowering the risk of accidental poisonings.

**- Safety and Efficiency:** Farmers and foragers will have access to advanced tools to accurately distinguish between safe and poisonous mushroom varieties, allowing them to make informed decisions during harvesting. This leads to safer practices in mushroom farming and foraging.

**- Mushroom Identification:** The feature can act as an educational resource, helping both farmers and the broader community learn more about mushrooms—specifically which features and environmental factors are linked to poisonous vs. edible mushrooms. This knowledge can empower individuals to forage responsibly.

**- Public Health Impact:** One of the most direct benefits is the potential to significantly reduce the number of mushroom poisoning cases, potentially saving lives. By providing real-time predictions about the safety of mushrooms based on their features and environmental factors, this tool could help prevent the estimated 100 deaths per year globally due to mushroom poisoning.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by deca109** [comment]
@manikumarreddyu this is a feature addition which according to GsSOC rules should be level2 at least. Can you please guide me how it is level1 as this is not about changing docs or fixing a minor bug?

**Comment by Sana1902** [comment]
can u please assign me this issue under gssoc-ext

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @deca109

**Comment by deca109** [comment]
> can you please let me know how much time do you need to complete this issue @deca109

I'll complete it within 3 days, sorry for the delay.

**Comment by deca109** [comment]
Hey @manikumarreddyu I am done with the model, I only need to make it into an API, I just need a day more to finish it, if you would reopen this issue. Apologies for the inconvenience (I was travelling).
