### ISSUE TITLE
[Feature Request]: Sugarcane Leaf Disease Detection

### ISSUE THREAD

**Issue by IkkiOcean** [manikumarreddyu/AgroTech-AI#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This project focuses on classifying sugarcane leaf diseases using different machine learning models. The dataset contains images of sugarcane leaves classified into various categories. Image preprocessing, data augmentation, and ensemble learning methods are applied to boost the model’s accuracy.

### Use Case

1.	Early Disease Detection:
	•	Farmers can detect diseases in sugarcane crops at an early stage, enabling timely intervention and minimizing crop damage
2.	Automated Crop Monitoring:
	•	The system can be integrated with drones or mobile apps to automatically monitor large sugarcane fields for disease symptoms, reducing the need for manual inspections.
3.	Improved Crop Management:
	•	With real-time disease detection, farmers can optimize pesticide use, applying treatments only when necessary, which reduces costs and minimizes environmental impact.
4.	Yield Improvement:
	•	Early and accurate disease detection helps farmers take proactive measures, leading to healthier crops and potentially increasing overall yield.
5.	Disease Pattern Analysis:
	•	Researchers and agronomists can use the classification system to study the prevalence and spread of different sugarcane diseases, helping in developing resistant crop varieties.
6.	Decision Support for Farmers:
	•	The model can be part of a decision support system that provides recommendations on disease management strategies based on the detected disease type.

### Benefits

The integration of sugarcane leaf disease classification into agrotech AI systems can offer several key benefits:
1.	Enhanced Crop Monitoring Capabilities:
	•	AgroTech AI systems equipped with disease classification models can provide real-time, automated crop health assessments, increasing efficiency in monitoring large-scale farms without the need for manual inspections.
2.	Cost Reduction:
	•	The early identification of diseases through AI reduces the need for blanket pesticide applications. Farmers can save costs by applying treatments only when necessary, leading to more targeted and efficient use of resources.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by IkkiOcean** [comment]
Pls assign me under gesso-extd and hacktoberfest

**Comment by Sana1902** [comment]
Can you please assign me this issue under gssoc-ext

**Comment by manikumarreddyu** [comment]
hi @Sana1902 thank you for your interest.
as of now @IkkiOcean is working very hard on this issue..
according to gssoc rules.admins cannot be able to assign one issue to more than one person at a time.

you can raise a new issue after exploring agrotech ai..you come up with new ideas
thank you @Sana1902 .
its great to have you in our contributors family here in agrotech ai..expecting more from you..
all the best.. @Sana1902

**Comment by IkkiOcean** [comment]
@manikumarreddyu I have my PR ready with a Ensemble model consisting of Vgg16, Conv2D, ResNet152 and InceptionV3 with accuracy of .
I'm putting the notebook in /notebooks directory with a model file (.h5). Is there anything else I should be aware of?

**Comment by manikumarreddyu** [comment]
dataset link in readme file along with project ->sugarcane leaf disease  detection description..

**Comment by IkkiOcean** [comment]
> dataset link in readme file along with project ->sugarcane leaf disease detection description..

I don't think I will be able to upload .h5 /.keras model files since the size exceeds its 100MB limit
