### ISSUE TITLE
[Feature Request]: Adding hover effect on buttons

### ISSUE THREAD

**Issue by iamsohelx** [manikumarreddyu/AgroTech-AI#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i wanted to add hover effect on buttons, which will enhance the user experience, and make the website look good

### Use Case

it will make the website look good

### Add ScreenShots

![hover](https://github.com/user-attachments/assets/2a4a0363-381b-482d-8e83-7acb572d673d)

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by iamsohelx** [comment]
@manikumarreddyu Thank you so much, i am a newbie, thank you so much for giving me this opportunity

**Comment by iamsohelx** [comment]
Hii @manikumarreddyu I have added the hower effect, can make I pull request?

https://github.com/user-attachments/assets/6bd847d1-0bca-4a6e-87e9-15d301ef7b28

**Comment by manikumarreddyu** [comment]
Go ahead

**Comment by manikumarreddyu** [comment]
Make it some what smooth...

**Comment by iamsohelx** [comment]
> Make it some what smooth...

Is it okay now? 

https://github.com/user-attachments/assets/3d3ef909-57e3-4705-84fe-cbae98312817

**Comment by manikumarreddyu** [comment]
Not okay....smooth transitions are important...for better user experience...try it using chatgpt if don't know..or reasearch about smooth transition hover effects in tailwind css
..
Make changes..and update here

**Comment by iamsohelx** [comment]
@manikumarreddyu Okay

**Comment by iamsohelx** [comment]
@manikumarreddyu now brother?

https://github.com/user-attachments/assets/09b06523-edd0-4e72-9dae-974a7cff54e5

**Comment by iamsohelx** [comment]
@manikumarreddyu if I am doing anything wrong please guide me brother, don't unassigned the issue please.

**Comment by manikumarreddyu** [comment]
Excellent work @iamsohelx make a PR...
please follow PR template exactly...

**Comment by iamsohelx** [comment]
@manikumarreddyu Yes, and thank you ☺️

**Comment by iamsohelx** [comment]
@manikumarreddyu 

> Excellent work @iamsohelx make a PR... please follow PR template exactly...

@manikumarreddyu Done Brother
