### ISSUE TITLE
[Feature Request]: Introducing GIF Backgrounds Specific to Temperature and Humidity Ranges

### ISSUE THREAD

**Issue by rebornstar1** [manikumarreddyu/AgroTech-AI#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Dynamic GIF backgrounds that change based on real-time temperature and humidity data. This feature aims to make the platform more visually engaging and provide users with an immersive experience by reflecting current weather conditions through animated backgrounds.

### Use Case

1. Users visiting the platform can immediately perceive the current weather conditions of a specific location through visually dynamic GIF backgrounds.
2. As a user views different temperature or humidity data, the background automatically changes to reflect those environmental conditions in real-time.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @rebornstar1

**Comment by rebornstar1** [comment]
Actually I was trying this but it's not looking good and maybe I think there's no need for this

**Comment by UTkARsh-RaJ01** [comment]
Can you assign this task to me?
