### ISSUE TITLE
[Feature Request]: Make the website Multilingual using google translate 

### ISSUE THREAD

**Issue by manikumarreddyu** [manikumarreddyu/AgroTech-AI#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Feature Request: We need to implement multilingual support for the Agrotech AI website to make it accessible to a wider audience, especially farmers from various regions.

### Use Case

enhance user experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by rebornstar1** [comment]
Can you please assign this issue to me

**Comment by AnushkaS77** [comment]
hey could you pls assign me as well @manikumarreddyu
