### ISSUE TITLE
[Feature Request]: Adding Dark Mode Toggle

### ISSUE THREAD

**Issue by sumitkumar9128** [manikumarreddyu/AgroTech-AI#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I’d love to see a dark mode toggle added to the site! It would be a great addition and compliment your website, especially for users who prefer darker themes or browse in low-light environments.

### Use Case

**What I’m Thinking:**

-There could be a toggle switch in the header that lets users easily switch between light and dark modes.
-When dark mode is turned on, any content that’s currently in black (or other dark colors) would automatically switch to lighter colors (like white or light gray) to keep everything readable and looking good.
-I will make sure all text, buttons, icons, and other interactive elements still pop and are easy to interact with in both modes.

### Benefits

**Why This Would Be Awesome:**

-It’ll improve accessibility for users who prefer dark mode or browse at night.
-Plus, it’s a cool, modern feature that users expect from sites nowadays

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sumitkumar9128** [comment]
Kindly assign this issue to me with the appropriate label. @manikumarreddyu

**Comment by AnushkaS77** [comment]
hey this feature this super cool...kindly assign me as well @manikumarreddyu

**Comment by manikumarreddyu** [comment]
hi @sumitkumar9128 please make sure to use dark property in tailwindcss..

**Comment by manikumarreddyu** [comment]
hi @AnushkaS77 first of all thank you for showing interest in this project..
according to rules of GSSOC ..the issues are assigned like first come..first serve..the admins must follow this rule..
i hope you got my point and also..in mean time you can create new issues in agrotech ai with some cool ideas and innovative thoughts..
thank you @AnushkaS77 
all the best...

**Comment by sumitkumar9128** [comment]
Thank you so much @manikumarreddyu  
I will take care of dark mode according to your need

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @sumitkumar9128

**Comment by sumitkumar9128** [comment]
Hi @manikumarreddyu ,

I wanted to provide a quick update regarding the dark mode feature. Implementing the feature itself isn't an issue; however, the main challenge I'm facing right now is cloning the repository to my local machine. I'm actively troubleshooting this, and once resolved, I'll proceed with the changes quickly.
![Screenshot 2024-10-09 095648](https://github.com/user-attachments/assets/2b330224-d0bb-4346-b391-ae5af458b9e1)


I appreciate your understanding, and I'll keep you posted as I work through this.
