### ISSUE TITLE
[Bug]: Incorrect image previews and inaccurate disease predictions generated by the AI engine

### ISSUE THREAD

**Issue by ShradhaSaxena23** [manikumarreddyu/AgroTech-AI#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Description:**
I have uploaded some images of plant leaves (Grape__Black_rot,Orange___Haunglongbing_(Citrus_greening)) from plantvillage dataset , the image displayed in the preview does not match the one I uploaded. Additionally, the disease predictions provided by the AI engine are incorrect and do not correspond to the actual condition of the leaf.

**Steps to Reproduce:**

Upload an image of a plant leaf.
Observe the image preview and compare it to the uploaded image.
Note the disease prediction provided by the AI model.

I have tested the image below and confirmed that the file path is correct-

![0cf5d61f-fb1a-4533-b0aa-f174d2acdc82___FAM_B Rot 0721](https://github.com/user-attachments/assets/646da1e3-fff2-43f3-a966-939db62ca60f)

![Screenshot 2024-10-06 234906](https://github.com/user-attachments/assets/fb132587-f36c-4222-96db-fe4a4e904638)

### Expected behavior

**Expected Behavior:**

The uploaded image should be displayed correctly in the preview.
The disease prediction should match the condition of the leaf in the uploaded image.

**Actual Behavior:**

The image shown in the preview is incorrect and does not match the uploaded image.
The disease prediction provided by the AI engine does not accurately reflect the condition of the plant leaf.

**Output from AI engine**

The image I uploaded was of a grape leaf affected by black rot, but the output is displaying an image of healthy corn. Additionally, the uploaded image and the previewed image do not match.

![Screenshot 2024-10-06 235027](https://github.com/user-attachments/assets/fa3a23fd-5d07-4264-bab1-15f0a34fb022)

### Add ScreenShots

![0cf5d61f-fb1a-4533-b0aa-f174d2acdc82___FAM_B Rot 0721](https://github.com/user-attachments/assets/7b16ca7e-640c-4b8e-a9cf-07be766c9d81)
![Screenshot 2024-10-06 234906](https://github.com/user-attachments/assets/c750c829-de8c-4330-9a32-5fe9b7d88897)
![Screenshot 2024-10-06 235027](https://github.com/user-attachments/assets/944d0039-52c7-42eb-8397-01e4620c1451)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @ShradhaSaxena23 please make sure to use tflite file only for model..

**Comment by manikumarreddyu** [comment]
In this PR youbjust work on image preview only...don't change the model..

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @ShradhaSaxena23

**Comment by ShradhaSaxena23** [comment]
I have requested you for PR
