### ISSUE TITLE
[Bug]: Text not visible in Rate us section and poor design.

### ISSUE THREAD

**Issue by Aum8** [manikumarreddyu/AgroTech-AI#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/user-attachments/assets/02c6c71b-6f27-43e6-9722-4f8eb5df7c97

### Expected behavior

The text should be visible. Also the dialog box shape is weird. I will make the rate us section look better and make it suit with the website theme. I am a Gssoc contributor, so please assign me this task under the required labels. Any suggestions from your side are appreciated.
Thanks.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by meghanakn473** [comment]
@manikumarreddyu can u assign me this issue

**Comment by manikumarreddyu** [comment]
Hi @meghanakn473 it is already assigned to someone
