### ISSUE TITLE
[Feature Request]: Dark Mode for Improved Accessibility and User Comfort.

### ISSUE THREAD

**Issue by Varsha567** [manikumarreddyu/AgroTech-AI#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As a GSSoC '24 extended contributor, I propose adding a dark mode to enhance user experience. Dark mode reduces eye strain in low-light environments and offers a modern user interface feature. I would like to contribute to implementing this feature.

### Use Case

Adding a dark mode would enhance the user experience by providing an option for users to switch to a visually comfortable interface, particularly in low-light environments. It reduces eye strain, conserves device battery life on OLED screens, and caters to user preferences for aesthetic customization. Additionally, having this option would align the platform with modern web design trends, making it more user-friendly and accessible to a wider audience, which can ultimately improve engagement with the project.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Varsha567** [comment]
Could you assign this to me?

**Comment by manikumarreddyu** [comment]
Check issue #127 ..it is already raised by others..
