### ISSUE TITLE
A Need of Farming Tools and Calculator

### ISSUE THREAD

**Issue by 1ShahidBashir** [manikumarreddyu/AgroTech-AI#136]
@manikumarreddyu There should be a List of Tools that farmers can benefit from the website.
Also a CALCULATOR should be implemented so a visitor can calculate how much of a particular fertiliser to buy for their land
![image](https://github.com/user-attachments/assets/7bf94b6b-7440-447a-9579-c988da8617fe)

**Comment by 1ShahidBashir** [comment]
@manikumarreddyu Assign this issue to me, we can look into it

**Comment by manikumarreddyu** [comment]
hi @1ShahidBashir create a option like tools in navbar..use drop down for that for different calculators...
is there any better idea ythan it..feel free to share here..
thank you @1ShahidBashir

**Comment by 1ShahidBashir** [comment]
@manikumarreddyu I am thinking of creating a page for tools since editing the index file can cause merge conflicts

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @1ShahidBashir

**Comment by manikumarreddyu** [comment]
Hi @1ShahidBashir anumy updates ?

**Comment by shalini-bhandari** [comment]
@manikumarreddyu kindly assign me this issue

**Comment by kartik3110** [comment]
@manikumarreddyu I can create the PR for this be EOD today

**Comment by manikumarreddyu** [comment]
you go ahead @kartik3110

**Comment by manikumarreddyu** [comment]
Any updates @kartik3110

**Comment by kartik3110** [comment]
Yes im done with the changes, but my vs code has formatted one of the files which has changed the indentation of it... If you want i can push right away or revert the indentation changes

**Comment by manikumarreddyu** [comment]
right click..and click on format document..
