### ISSUE TITLE
[Feature Request]: Authentication and in weather image.

### ISSUE THREAD

**Issue by SunkaraboinaPraveenKumar** [manikumarreddyu/AgroTech-AI#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Authentication can be provided using clerk

In Weather we can use a place api to fetch image of that place and weather conditions as well

### Use Case

to identify and track user and his profile

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SunkaraboinaPraveenKumar** [comment]
![Uploading Screenshot (148).png…]()

**Comment by manikumarreddyu** [comment]
Hi @SunkaraboinaPraveenKumar ..I think...the weather forecast which is already there 
.is good..it need some extra features like...
Hourly
Daily
Weekly
Monthly
Yearly
Type of functions...so that user can see what ever he wants...

If you have a new idea raise a new issue...I am closing this one...

**Comment by SunkaraboinaPraveenKumar** [comment]
I can do hourly and daily with reactjs and using beautiful toasts.

**Comment by manikumarreddyu** [comment]
hi @SunkaraboinaPraveenKumar raise anew issue by following issue template.. iw ill assign you..please do it perfectly by not changing the existing look and design..
thank you @SunkaraboinaPraveenKumar

**Comment by SunkaraboinaPraveenKumar** [comment]
Thank You i will raise but once have a look at your app weather functionality is not working well i think

**Comment by SunkaraboinaPraveenKumar** [comment]
Yesterday it worked well

**Comment by SunkaraboinaPraveenKumar** [comment]
Another Thing If You Feel like Chatbot is necessary in can do that as well if weather is not that important

**Comment by SunkaraboinaPraveenKumar** [comment]
I will raise an issue if none are working on it

**Comment by manikumarreddyu** [comment]
hi @SunkaraboinaPraveenKumar you first work on chat bot...later you can do weather

**Comment by manikumarreddyu** [comment]
when it comes to workinng of weather..the api calls limit is over..i just updated the api key...it is working fine now..

**Comment by SunkaraboinaPraveenKumar** [comment]
Ok Bro I will work on Chatbot i will raise issue
