### ISSUE TITLE
[Feature Request]: Improvement and fix bug in rate us form

### ISSUE THREAD

**Issue by ananyag309** [manikumarreddyu/AgroTech-AI#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the font colour of rate me form message needs to be changed as it is not visible moreover instead of getting confirmation message via alert it will be great if we use popup confirmation message for better user experience 
![image](https://github.com/user-attachments/assets/33eae1ab-0abf-46bf-b267-dce2d01a4e7e)

### Use Case

n/a

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Already there
