### ISSUE TITLE
[Bug]: Adding social icons in place of static social links

### ISSUE THREAD

**Issue by tarunkumar2005** [manikumarreddyu/AgroTech-AI#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[Bug]: Adding social icons in place of static social links. here in the image shown the links are text which is not good for ui/ux and gives a bad impression to user.

### Expected behavior

We need to add the social media icons for that and properly enhance the ui/ux so that it provides best  output to the user needs.

Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/802cd627-e52e-496a-9fa5-a75743412062)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @tarunkumar2005

**Comment by tarunkumar2005** [comment]
@manikumarreddyu Will do it today only i will create a PR before 7or8 pm today. Is it okay

**Comment by manikumarreddyu** [comment]
can you make it before 12 pm today.. @tarunkumar2005

**Comment by tarunkumar2005** [comment]
@manikumarreddyu Will try to do that if possible and i get some time.

**Comment by tarunkumar2005** [comment]
@manikumarreddyu I think it is already fixed so i can't do anything

![image](https://github.com/user-attachments/assets/128251a2-57be-491d-8422-a07242c47a9d)

**Comment by tarunkumar2005** [comment]
or i forgot where i took the screenshot if you find somewhere can you tell me part part of website the issue was there i will fix that i have time now you know website better than me if you see where it is.

**Comment by manikumarreddyu** [comment]
See in contact us page

**Comment by manikumarreddyu** [comment]
Go to contact us page..ther you will definitely find

**Comment by manikumarreddyu** [comment]
Wait I'm searching for it

**Comment by manikumarreddyu** [comment]
https://github.com/manikumarreddyu/AgroTech-AI/pull/164/files

Somebody ruined it...

Can you fix this..

**Comment by tarunkumar2005** [comment]
@manikumarreddyu Ya will fix it i think it is taken from ai that's why it gives comments there and he/she didn't checked that will do that soon.

**Comment by tarunkumar2005** [comment]
@manikumarreddyu I have created the PR and i found where my issue was i will fix that also he/she commented that part out that's why i was not seeing it.

**Comment by tarunkumar2005** [comment]
@manikumarreddyu done bro icons are changed see the pull request.
