### ISSUE TITLE
[Feature Request]: Weather App

### ISSUE THREAD

**Issue by SunkaraboinaPraveenKumar** [manikumarreddyu/AgroTech-AI#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Would Like to integrate weather app with hourly and daily features.

### Use Case

The farmers can see daily and hourly weather accurately such that fertilizer application, pesticides application and some agricultural tasks needed weather not be rainy such info can be obtained.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SunkaraboinaPraveenKumar** [comment]
Please assign me under hacktoberfest

**Comment by manikumarreddyu** [comment]
make a comment in chatbot issue..i will assign you...and how many days do you want to do it completely..?

https://www.linkedin.com/in/manikumarreddyu
connect me here.. we will discuss

**Comment by SunkaraboinaPraveenKumar** [comment]
I will try in one day as i am completely free now due to dasara holidays

**Comment by manikumarreddyu** [comment]
it is completed @SunkaraboinaPraveenKumar ...we are developing application so fast..i think you understand
thank you @SunkaraboinaPraveenKumar
