### ISSUE TITLE
[Feature Request]: Chatbot for farmers. Assign me under hacktoberfest.

### ISSUE THREAD

**Issue by SunkaraboinaPraveenKumar** [manikumarreddyu/AgroTech-AI#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Chatbot in Agriculture related with neat UI.

### Use Case

It would be a great help for farmers these days youth who are little bit educated who know who to operate mobile an make use of this for instant anwers to their queries.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
how many days do you want ??

**Comment by SunkaraboinaPraveenKumar** [comment]
I will try it in one day mostly as i am completely free due to Dasara Holidays.

**Comment by SunkaraboinaPraveenKumar** [comment]
Finished It Actually I have made it previously in Python and did seperately in Web Development with another api now integrated both once have a look and please try to accept my PR

**Comment by SunkaraboinaPraveenKumar** [comment]
Also Once have a look at my weather app completely bro
https://weather-flask-kbv1.onrender.com/
I had just uploaded first image scroll up it can show humidity, min ,max temerature, sunrise sun set time as well
