### ISSUE TITLE
Feature: Frontend - Implement Login and Signup UI

### ISSUE THREAD

**Issue by harish08102004** [manikumarreddyu/AgroTech-AI#153]
Develop the user interface for the Login and Signup functionality, with form validation and integration with the backend API for user registration and authentication.

**Tasks**:

- Design a Signup form with fields: username, email, and password.
- Design a Login form with fields: email/username and password.
- Perform input validation (password strength, valid email, etc.).
- Provide user feedback for successful or failed registration/login attempts.
- Redirect users to the dashboard after successful login.
- Ensure the UI is responsive and user-friendly.

**Feature Requirements**:

- Integrate the forms with the backend API for user registration and authentication.
- Store JWT tokens in local storage or cookies for session management after login.
- Display error messages for invalid credentials or form errors.
- Handle successful registration/login with redirection and session management.

Hey @manikumarreddyu I can work on it.

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @harish08102004

**Comment by manikumarreddyu** [comment]
hi @harish08102004 ..any updates..?
