### ISSUE TITLE
[Feature Request]: Build Backend API for Sugarcane Disease Prediction Model

### ISSUE THREAD

**Issue by IkkiOcean** [manikumarreddyu/AgroTech-AI#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to implement the backend API for predicting sugarcane leaf diseases as part of the Agrotech AI platform. The model has been developed and trained using various machine learning techniques, and now we need to integrate it into the backend to make it accessible via API requests.

1.	User Input:
	•	A farmer or agricultural technician uploads an image of a sugarcane leaf to the Agrotech AI platform, which is then sent to the backend API for analysis.
	2.	Backend Process:
	•	The backend API receives the image via a POST request.
	•	The API preprocesses the image (resizing, normalization, etc.) and feeds it into the sugarcane disease prediction model.
	•	The model predicts the type of disease (or healthy leaf) along with a confidence score.
3.	Response:
	•	The API returns a JSON response containing:
	•	Predicted disease type (e.g., “Red Rot”, “Brown Rust”, etc.)
	•	Confidence score for the prediction (e.g., 85% confident).

### Use Case

The API empowers farmers with instant, reliable predictions about sugarcane leaf diseases, helping them to make informed decisions and prevent further crop damage.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @IkkiOcean for frontend create separate issue..is that okay for you..?

**Comment by IkkiOcean** [comment]
> hi @IkkiOcean for frontend create separate issue..is that okay for you..?

Yeah I will. Should I create the issue now?
