### ISSUE TITLE
[Feature Request]: Create Frontend for Sugarcane Disease Prediction

### ISSUE THREAD

**Issue by IkkiOcean** [manikumarreddyu/AgroTech-AI#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to design and implement the frontend interface for the sugarcane disease prediction feature of the Agrotech AI platform. The frontend will allow users (farmers, technicians) to upload images of sugarcane leaves, receive predictions from the backend API, and display the results clearly.

### Use Case

The frontend will provide an intuitive interface for farmers to easily upload images and receive disease predictions, ensuring a smooth user experience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @IkkiOcean

**Comment by IkkiOcean** [comment]
> can you please let me know how much time do you need to complete this issue @IkkiOcean 
 
Till tomorrow. Though I will try to finish both the backend and frontend today itself.
