### ISSUE TITLE
[Feature Request]: Community Forum

### ISSUE THREAD

**Issue by manikumarreddyu** [manikumarreddyu/AgroTech-AI#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

.

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by J-B-Mugundh** [comment]
Please assign me this task!

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @J-B-Mugundh

**Comment by J-B-Mugundh** [comment]
This issue is actually dependant on #59 where someone else is assigned to create login and sign up with users collection in mongodb. Once it's done, I could finish this in 1 or 2 days max.
