### ISSUE TITLE
[Bug]: Crop Recommendation in the Crops Section is accepting values beyond its permissible limit and needs to be fixed

### ISSUE THREAD

**Issue by rebornstar1** [manikumarreddyu/AgroTech-AI#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "Crop Recommendation" feature in the Crops section is currently accepting input values that exceed the defined permissible limits. This issue could lead to inaccurate recommendations and incorrect functionality. It appears that validation checks are either missing or not correctly implemented, allowing users to input values outside the acceptable range.

### Expected behavior

Input validation should be implemented to ensure that only values within the permissible limits are accepted.
Proper error handling and feedback should be provided when an invalid value is entered.
The system should display accurate recommendations based on valid input values.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
its not a problem...we just provided for reference..
