### ISSUE TITLE
[Feature Request]: Refactor Article Page Styling to Use Tailwind CSS Instead of External CSS

### ISSUE THREAD

**Issue by IkkiOcean** [manikumarreddyu/AgroTech-AI#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to refactor the existing styling of the article page by replacing the external CSS with Tailwind CSS for better consistency and maintainability across the project. This change will allow for faster development, reduced CSS file sizes, and more flexibility in design.

### Use Case

•	The page loads faster due to reduced custom CSS, leveraging Tailwind’s smaller, utility-based classes that are only included in the final build.

### Add ScreenShots

<img width="1280" alt="Screenshot 2024-10-08 at 6 19 57 PM" src="https://github.com/user-attachments/assets/bb7a43fc-c5ff-4e1d-9bb6-f8d20dbdfb14">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by IkkiOcean** [comment]
I have already removed the external css and added tailwind css to the page. just assign me the issue to I can make the PR.

**Comment by manikumarreddyu** [comment]
uou go ahead @IkkiOcean
