### ISSUE TITLE
Scrolling of BackToTop Button is nt smooth

### ISSUE THREAD

**Issue by Shariq2003** [manikumarreddyu/AgroTech-AI#184]
https://github.com/user-attachments/assets/4ef5b293-eefd-4101-a981-6345297fa4d6

Please assign this to me, I will smooth the scrolling

**Comment by manikumarreddyu** [comment]
https://agro-tech-ai.vercel.app/

check this once

**Comment by Shariq2003** [comment]
> https://agro-tech-ai.vercel.app/
> 
> check this once

Still same

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @Shariq2003

**Comment by Shariq2003** [comment]
@manikumarreddyu Hi, after raising the issue , I was gone to bad. Well,  it's a 10-minute work. I will raise PR by today after getting free of college 🥲

**Comment by Shariq2003** [comment]
Now, i am working, will raise the PR in next 10-15mints max.

**Comment by manikumarreddyu** [comment]
hi @Shariq2003 i have not seen any changes...i am closing the PR..i m sorry
