### ISSUE TITLE
[Feature Request]: Increase size of the text in navbar when we hover on them

### ISSUE THREAD

**Issue by saiprasanna56** [manikumarreddyu/AgroTech-AI#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhance the user experience by increasing the text size of navbar items when users hover over them. This visual feedback will indicate that the items are interactive and can be clicked, making navigation more intuitive.

### Use Case

The feature of increasing the text size in the navbar on hover will provide users with immediate visual feedback, making navigation more intuitive and engaging.

### Benefits

Enhanced User Experience: Provides clear indicators of interactivity, making navigation intuitive.
Accessibility Improvement: Ensures effective navigation for users with visual impairments.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
<img width="119" alt="image" src="https://github.com/user-attachments/assets/c14766a2-b075-4d39-a4ed-82cad0a0edba">

make like this when hovered and if a user is in home page..the home should look like this..having rounded square box ..highlightig that he is currently in home page..

i think you got my point @saiprasanna56

**Comment by manikumarreddyu** [comment]
how much time do you need to complete this issue @saiprasanna56

**Comment by saiprasanna56** [comment]
@manikumarreddyu is this ok 
![image](https://github.com/user-attachments/assets/e4cb76e6-874c-4dde-bed7-4e3697370302)
