### ISSUE TITLE
[Bug]: Cards are not working properly under the disease section

### ISSUE THREAD

**Issue by sriraghavi22** [manikumarreddyu/AgroTech-AI#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. When the cursor is pointed at the card it should turn and when it is removed it should come to its original state but it is not coming to its original state.
2. The card should have a button called read more as only half of the text is visible.
3. The card should have its own heading at the back. If it is about apple then it should have apple as heading as it is difficult for user to turn it over again and again to see what is he reading.

### Expected behavior

1. The card should return to its original state when cursor is removed
2. Read more button should be added
3. Should have a heading regarding what it is describing

### Add ScreenShots

https://github.com/user-attachments/assets/29ffd761-47b7-4942-af65-b564cead9875

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sriraghavi22** [comment]
Hey @manikumarreddyu , Can i know y are the issues closed?

**Comment by manikumarreddyu** [comment]
when it comes to follow us icons ..they are tilting..it is not a bug ..it is feature..
you can work on this.. @sriraghavi22

**Comment by 0sigma101** [comment]
@manikumarreddyu , I am Mentor Assigned for the project. Can you please give rights to review the codes or maintainer rights.

**Comment by manikumarreddyu** [comment]
hi @sriraghavi22 can you please let me know..how much time do you need to fix this issue..?

**Comment by manikumarreddyu** [comment]
https://agro-tech-ai.vercel.app/

hi @sriraghavi22 can you please stop working on it....because we updated it..

**Comment by manikumarreddyu** [comment]
https://www.linkedin.com/in/manikumarreddyu connect me here..if you have any doubts
