### ISSUE TITLE
[Feature Request]: Adding A Certification and Gradation

### ISSUE THREAD

**Issue by Mandy1200** [manikumarreddyu/AgroTech-AI#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

First i will set the select language set , on the top body constant on every page

then in place of it  , I will add a certification and gradation section

in that i will add different courses , launched schemes by goverment and many more , incuding all other required elements on the main page

### Use Case

It will be more useful for the farmers  and it the website will gain more reach with more information attached in a single page 

### Benefits

As everything available in the section , but their is no option for Certification and Gradation of farmers , as it is most required for the verification and substantiation of the farmers

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @Mandy1200 as of now we dont require this feature..
