### ISSUE TITLE
Crop Recommendation System Based on Soil Data

### ISSUE THREAD

**Issue by Aditijainnn** [manikumarreddyu/AgroTech-AI#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add ml model Crop Recommendation System Based on Soil Data

### Use Case

propose an Intelligent Crop Recommendation and Yield prediction system using Machine Learning that predicts crop suitability by factoring all relevant data such as temperature, rainfall, location, and soil condition.
assign his to me under gssoc ext and hacktiberfest

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Already there @Aditijainnn
