### ISSUE TITLE
[Feature Request]: Adding hover effect for advantages and disadvantages in crop section

### ISSUE THREAD

**Issue by saiprasanna56** [manikumarreddyu/AgroTech-AI#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "Hover Effect for Advantages and Disadvantages in the Crop Section" feature adds visual feedback when users hover over items in these sections. This includes changes like background color, font weight, or shadows to highlight the hovered item, enhancing interactivity and improving readability without altering the main code structure. The effect will make the content more engaging and user-friendly.

### Use Case

This feature would enhance the project by improving user engagement and navigation. By providing immediate visual feedback when hovering over advantages and disadvantages, users can quickly identify key points, making the content more interactive and easier to digest. It also adds a layer of professionalism and polish to the user interface, improving the overall user experience.

### Benefits

The hover effect improves user experience by enhancing navigation, making the interface more interactive and accessible. It adds a polished, professional look, increases user engagement, and improves information clarity, benefiting both the project and the community.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @saiprasanna56 there is no need of this feature...i hope you get it..
