### ISSUE TITLE
[Feature Request]: Add hover effect on FAQ

### ISSUE THREAD

**Issue by jvkousthub** [manikumarreddyu/AgroTech-AI#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It would look more appealing if there could have been an effect upon hiver on FAQ question

### Use Case

It will look more good

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by jvkousthub** [comment]
@manikumarreddyu I would like to work on this issue

**Comment by manikumarreddyu** [comment]
https://style-share.vercel.app/app/

hi @jvkousthub can you make faq section in agrotech like https://style-share.vercel.app/app/ in this app...use colors in agrotech but with same functinalities in https://style-share.vercel.app/app/

**Comment by manikumarreddyu** [comment]
can you please complete it by today evening...or ASAP @jvkousthub
