### ISSUE TITLE
[Feature Request]: Clicking on the logo should redirect to home page

### ISSUE THREAD

**Issue by jvkousthub** [manikumarreddyu/AgroTech-AI#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Suppose the user is at some part of the page and if the ser clicks on the logo he will reach to the home page, like it happens in most of the sites

### Use Case

It would be easier to navigate to home page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by jvkousthub** [comment]
@manikumarreddyu Please assign me this issue

**Comment by manikumarreddyu** [comment]
hi @jvkousthub can you please  complete it before 2pm..today..as it is a small isuue right..

**Comment by jvkousthub** [comment]
> hi @jvkousthub can you please complete it before 2pm..today..as it is a small isuue right..

I'll try, mostly it'll be done

**Comment by jvkousthub** [comment]
> hi @jvkousthub can you please complete it before 2pm..today..as it is a small isuue right..

Made a PR please review
