### ISSUE TITLE
[Bug]: Chatbot Not responding

### ISSUE THREAD

**Issue by mayankjain2710** [manikumarreddyu/AgroTech-AI#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when i ask query on chatbot is not responding after sending enough query

### Expected behavior

i expect that chatbot should readily response for user query and resolve their issue as soon as possible 

### Add ScreenShots

![Screenshot (211)](https://github.com/user-attachments/assets/5a284c16-c2a1-4cf3-bff7-686b0d70eacd)

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by mayankjain2710** [comment]
I feel i make to contribute in this issue by making interactive and responsive chatbot

**Comment by manikumarreddyu** [comment]
There will be a 1 minute delay for first response...after that everything is quick

**Comment by manikumarreddyu** [comment]
Check it

**Comment by mayankjain2710** [comment]
Yes it work but improving the time delay is necessary for user experience

**Comment by manikumarreddyu** [comment]
Where will you deploy...when it is used in local there will be no delay at all..as we are using free version of render for api deployment..it is delaying 50 seconds ..do you have any other solutions for deployment @mayankjain2710

**Comment by mayankjain2710** [comment]
I thought making this chatbot using javascript because it get quick response and decrease the time delay at some amount as compared to python

**Comment by manikumarreddyu** [comment]
Can you make it powerful.. so that...it can answer any question related to agriculture.?
As of now we are using groq .which is powerful enough to answer all questions...can you make it...?

**Comment by mayankjain2710** [comment]
I will try my best to make it

**Comment by manikumarreddyu** [comment]
Ok then...if it fails to meet the expectations...I will not merge...is it okay for you..?

**Comment by mayankjain2710** [comment]
Ok, so I will also not get points for the contribution.

**Comment by manikumarreddyu** [comment]
Are you going to get it from agrosage..which is there in your repos... @mayankjain2710 
Can you share any related video...how it works...which you are going to build

**Comment by mayankjain2710** [comment]
yes i will provide you working video and sorry for late response

**Comment by mayankjain2710** [comment]
https://youtu.be/BJhBn-gzaOE?si=be5_mkHVfnGVwW4M
here is the link of working video

**Comment by manikumarreddyu** [comment]
dont remove the existing chatbot..just add yours and place it bottom left..

**Comment by mayankjain2710** [comment]
You mean not remove existing chatbot and also add another chatbot at left right

**Comment by manikumarreddyu** [comment]
YES

**Comment by manikumarreddyu** [comment]
https://www.linkedin.com/in/manikumarreddyu/

Connect me here

**Comment by mayankjain2710** [comment]
ok

**Comment by manikumarreddyu** [comment]
are you willing to do or not ?

**Comment by mayankjain2710** [comment]
yes sir

**Comment by manikumarreddyu** [comment]
you go ahead...you can start working on it

**Comment by mayankjain2710** [comment]
ok sir and sir their is time limit to done submit it

**Comment by manikumarreddyu** [comment]
try to complete ASAP

**Comment by manikumarreddyu** [comment]
please let me know how much time do you need to complete this issue @mayankjain2710

**Comment by mayankjain2710** [comment]
I complete this work by 13 oct

**Comment by manikumarreddyu** [comment]
ok
