### ISSUE TITLE
[Feature Request]: Black Rot disease

### ISSUE THREAD

**Issue by meghanakn473** [manikumarreddyu/AgroTech-AI#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Black Rot: Common in cruciferous vegetables like cabbage and broccoli, leading to black spots and rotting of the leaves and stems.
So i want to add this disease info with appropriate image of it 

@manikumarreddyu  please assign me this issue under level 3, gssoc-extd, hacktoberfest

### Use Case

Knowing about Black Rot helps in early detection and management, preventing crop losses and ensuring better yield quality.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Hi @meghanakn473 if you can able make both frontend and api ...I will assign you...otherwise I can't .. because having just notebook files..doesn't make any sense at all..I hope you got it

**Comment by manikumarreddyu** [comment]
I'm closing this issue...if you are able to do frontend and api..I will reopen it again..I hope you got it @meghanakn473
