### ISSUE TITLE
[Feature Request]: Redesigning the UI for Prediction Model, What users say and FAQ in Home page with elegant look and better UI Experience

### ISSUE THREAD

**Issue by rebornstar1** [manikumarreddyu/AgroTech-AI#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The redesign of the Prediction Model, What Users Say, and FAQ sections on the home page focuses on enhancing the visual appeal and user experience. By implementing modern design principles, the sections will be more visually engaging, intuitive, and responsive, allowing users to easily access critical information about the prediction model, customer feedback, and frequently asked questions.

### Use Case

Prediction Model Access: Users can quickly understand the capabilities of the prediction model through an engaging layout, helping farmers make informed decisions about crop management.

User Testimonials: Potential customers can easily view organized testimonials from existing users, fostering trust and encouraging new users to explore the platform.

FAQ Navigation: Users can swiftly find answers to common queries in a well-structured FAQ section, enhancing user satisfaction and reducing support inquiries.

### Benefits

Enhanced User Engagement: A visually attractive and well-organized design captures users' attention, encouraging them to explore the site further and increasing their time on the platform.
Improved Clarity and Understanding: Clear, concise, and aesthetically pleasing presentations of the prediction model and user testimonials help users grasp key information quickly, leading to informed decision-making.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
you can go ahead.. @rebornstar1
