### ISSUE TITLE
[Feature Request]: Add crop yield calculator used for farmers 

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [manikumarreddyu/AgroTech-AI#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add crop yield calculator used for farmers 

### Use Case

FArmers can calculate how much yeild they can obtain

### Benefits

useful for farmers

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Can you please share any demo video of how this feature works... @KapuluruBhuvaneswariVspdbct

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
https://github.com/user-attachments/assets/f08b601e-febc-458f-afa7-db096b08ab71

please have a look it is used to calculate no of kgs of yield can be produced

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
wanted to work on this
