### ISSUE TITLE
[Feature Request]: soil moisture calculator

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [manikumarreddyu/AgroTech-AI#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

soil moisture calculates moisture in the soil

### Use Case

calculates moisture in soil

### Benefits

Helpful to farmers

### Add ScreenShots

This is the preview of how it works
https://github.com/user-attachments/assets/d478ebad-f478-4296-bc6e-2bd4ab237f9a

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
wanted to work on it

**Comment by vijaychandra1910** [comment]
please assign it to me @manikumarreddyu

**Comment by manikumarreddyu** [comment]
it is already assigned to @KapuluruBhuvaneswariVspdbct ..
