### ISSUE TITLE
[Feature Request]: create Virtual calculators for agriculture  

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [manikumarreddyu/AgroTech-AI#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We include all the virtual calculators to calculate the agriculture needs in the website 

### Use Case

used by farmers to calculate agriculture needs

### Benefits

Farmers get benifited by this

### Add ScreenShots

calculators like this will be grouped in a page

https://github.com/user-attachments/assets/a3a1cf0a-697a-4225-8e27-8118719c631d

https://github.com/user-attachments/assets/ba7c6c9d-b915-4a38-9dd0-ee5dafaf7290

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
wanted to work on it

**Comment by manikumarreddyu** [comment]
already assign in previous ones..soo closing this issue...
