### ISSUE TITLE
[Feature Request]: Adding toggle dark mode

### ISSUE THREAD

**Issue by 23wh1a0513** [manikumarreddyu/AgroTech-AI#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The toggle for dark mode gives users the flexibility to choose the interface that best suits their needs and preferences.

### Use Case

The toggle for dark mode gives users the flexibility to choose the interface that best suits their needs and preferences.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
it is already there..i just hid that feature wantedly...so no worries @23wh1a0513 ..after complteing the website whole..we can enable it.. and we will work on it.. @23wh1a0513

**Comment by 23wh1a0513** [comment]
ok
