### ISSUE TITLE
[Feature Request]: Add Crop Suitability Prediction

### ISSUE THREAD

**Issue by pavitraag** [manikumarreddyu/AgroTech-AI#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Recommends the most suitable crops for a given piece of land based on soil type, climate, and environmental factors.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
can you please share me the working video of this feature.. @pavitraag

**Comment by pavitraag** [comment]
@manikumarreddyu May i kn the reason to close this...this isn't present in your website right

**Comment by manikumarreddyu** [comment]
Working demo video...

**Comment by pavitraag** [comment]
@manikumarreddyu I will raise the pr by tomorrow
