### ISSUE TITLE
[Feature Request]: add water requirement calculator 

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [manikumarreddyu/AgroTech-AI#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add water requirement calculator

### Use Case

it helps to calculate amount of water rrequired

### Benefits

helps farmers to know amount of water required

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Sir finding issue while cloning showing already contain folders gir can
clone empty files

**Comment by manikumarreddyu** [comment]
https://www.linkedin.com/in/manikumarreddyu/

connect me here
