### ISSUE TITLE
[Feature Request]: Add seed rate calculator 

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [manikumarreddyu/AgroTech-AI#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add seed rate calculator 

### Use Case

used by farmers to calculate seed rate

### Benefits

helpful to farmers

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Sir finding issue while cloning showing already contain folders gir can clone empty files

**Comment by manikumarreddyu** [comment]
https://www.linkedin.com/in/manikumarreddyu/

connect me here..please
