### ISSUE TITLE
[Feature Request]: Add the Explore more page, which includes all the features categorized and arranged.

### ISSUE THREAD

**Issue by Jay-1409** [manikumarreddyu/AgroTech-AI#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Explore features page
- Contain all the features in an organized manner
- easy to locate a feature
- theme stays intact 

### Use Case

Will help the users navigate through the features easily
- Descriptions of the features
- benefits of the features
- link to the feature

### Benefits

Saves confusion and time .
Gives purpose to the explore now button
Better UI

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Can you please try to complete it by EOD 9PM

**Comment by Jay-1409** [comment]
Okay ill do it!!

**Comment by manikumarreddyu** [comment]
Sent a request in linkedin connect ..we will discuss there
