### ISSUE TITLE
[Feature Request]:Eco-Crop Manager 

### ISSUE THREAD

**Issue by 23wh1a0513** [manikumarreddyu/AgroTech-AI#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Aims to raise awareness about sustainable farming practices, pest management, and the relationship between crops and their environment.

### Use Case

Enhance their understanding of agricultural practices, specifically involving crop selection, soil types, seasonal planting, and pesticide application.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by 23wh1a0513** [comment]
@manikumarreddyu i would like to work on it.

**Comment by 23wh1a0513** [comment]
https://github.com/user-attachments/assets/da08ef59-6a4e-4ce3-a44e-f06f48160888

here is the demo how it works

**Comment by manikumarreddyu** [comment]
Raise the pr

**Comment by 23wh1a0513** [comment]
> Raise the pr

OK
