### ISSUE TITLE
[Feature Request]: Applying better design and UI for Price Prediction page .

### ISSUE THREAD

**Issue by rebornstar1** [manikumarreddyu/AgroTech-AI#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current Price Prediction page lacks a modern design and intuitive user interface, making it difficult for users to efficiently interpret price trends and predictions. The layout is cluttered and does not effectively highlight key data, leading to a subpar user experience. Given the importance of price forecasting in agricultural decision-making, applying a more user-friendly design and improved UI is necessary to provide clear insights and enhance usability.

### Use Case

A farmer or trader visits the Price Prediction page to analyze market trends and forecast the future prices of crops. However, due to the page’s outdated design and non-intuitive interface, they struggle to quickly grasp crucial insights or perform price comparisons. By applying a better design and UI, users will be able to easily understand the predictions, analyze trends, and make well-informed market decisions, leading to better financial outcomes.

### Benefits

Improved Data Clarity: A better design will make price trends and predictions more visually accessible, helping users quickly interpret and act on market insights.
User-Friendly Interface: A more intuitive UI will reduce friction for users, allowing both experts and newcomers to easily navigate the platform and find the information they need.
Efficient Decision-Making: With clearer, well-organized data and improved usability, users can make faster, more informed pricing decisions, boosting their market efficiency.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Hi @rebornstar1 any updates on this... complete this ASAP

**Comment by badmuffin** [comment]
Hi @manikumarreddyu, it seems like @rebornstar1 hasn't responded, and it's been a week since the issue was raised. If possible, could you assign the task to me? I would be happy to work on it.

**Comment by rebornstar1** [comment]
I'll submit the PR by tonight, The Designing of the page is almost done

**Comment by Vansh-134** [comment]
Assign this to me
