### ISSUE TITLE
[Feature Request]: Seed Quality Prediction Model (API)

### ISSUE THREAD

**Issue by LitZeus** [manikumarreddyu/AgroTech-AI#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This API implements a Convolutional Neural Network (CNN) model to classify seed quality based on a dataset of seed images. The model is trained to predict whether seeds are of premium, standard, or regular quality by analyzing visual characteristics such as size, color, and texture. The primary goal is to ensure high crop productivity by making accurate seed quality predictions. The API will also provide a validation mechanism to ensure consistent and reliable seed classification, addressing the inefficiencies present in manual human intelligence-based evaluations.

### Use Case

In agriculture, particularly in India, where manual seed quality prediction is common, this API can significantly improve farming operations. For example, a seed distributor could use the API to analyze large batches of seeds before sale, ensuring that only high-quality seeds are distributed to farmers. Similarly, a farmer could use the API to validate seed quality before planting, improving crop yield by planting only the best seeds. This would be especially beneficial during high-scale agricultural planning, where even small improvements in seed selection can have a large impact on output.

### Benefits

- **Improved Accuracy**: By using a CNN model, the API ensures precise seed classification, leading to higher prediction accuracy than traditional methods.
- **Scalability:** The model can handle large datasets and be applied across different seed varieties and regions, making it useful for large-scale farming and distribution networks.
- **Efficiency:** Automating seed quality evaluation reduces the time and effort spent on manual inspection, making the process more efficient and less prone to human error.
- **Higher Crop Yield:** Farmers can rely on this API to make informed decisions on seed quality, leading to better germination rates and higher crop production.
- **Validation Mechanism:** The API provides a reliable and consistent validation mechanism, filling the gap left by traditional, knowledge-based prediction methods without any validation.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
are you going to do both frontend and api.. @LitZeus

**Comment by LitZeus** [comment]
i would like to start by adding the backend first.
Right now API only if it is fine with you!
@manikumarreddyu

**Comment by LitZeus** [comment]
Thanks! @manikumarreddyu
