### ISSUE TITLE
[Feature Request]: Enhanced styles and formatting

### ISSUE THREAD

**Issue by J-B-Mugundh** [manikumarreddyu/AgroTech-AI#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

.

### Use Case

.

### Benefits

.

### Add ScreenShots

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Charul00** [comment]
can you please assign to me also @J-B-Mugundh
