### ISSUE TITLE
[Feature Request]:  improving chatbot

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [manikumarreddyu/AgroTech-AI#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the current chatbot consumes up all the same , i can give u a better chatbot which will be a popup on the rightside and only consume little place.

### Use Case

<img width="1464" alt="Screenshot 2024-10-12 at 7 05 27 AM" src="https://github.com/user-attachments/assets/b07a91e6-fe56-41ef-9a6a-d59406334898">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
It is the feature we wanted for this chatbot

. currently working on a chatbot with pure javascript...

**Comment by manikumarreddyu** [comment]
See issue #302
