### ISSUE TITLE
[Feature Request]: improving UI of the form and adding local storage

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [manikumarreddyu/AgroTech-AI#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add a local storage to save the user input and also improve the form features.

### Use Case

<img width="1464" alt="Screenshot 2024-10-12 at 7 07 54 AM" src="https://github.com/user-attachments/assets/bd723613-1a26-4c86-9203-69ce17a3dd26">

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
We are working on backend...it is not needed...

**Comment by manikumarreddyu** [comment]
See #218
