### ISSUE TITLE
[Bug]: Contact Page needs improvement

### ISSUE THREAD

**Issue by nksmanya** [manikumarreddyu/AgroTech-AI#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The follow us on socials is repeated twice in the contact section.

### Expected behavior

I would like to work on this issue and solve it. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a7fb44b2-acef-4f6d-87b5-f9c2d3d06594)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
see #218
