### ISSUE TITLE
[Bug]: ChatBot not fitting in the page properly

### ISSUE THREAD

**Issue by nidhi752** [manikumarreddyu/AgroTech-AI#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The chatbot is not displaying correctly on the page. It either overflows the boundaries of its container or appears misaligned, resulting in parts of the chatbot being cut off or hidden. This issue affects its usability and responsiveness, making it difficult for users to interact with the chatbot on different screen sizes. The expected behavior is that the chatbot should resize and fit properly within the available space on the page, adapting seamlessly to different device dimensions.

### Expected behavior

The expected behavior is that the chatbot should be fully visible and properly aligned within its designated container on the page. It should automatically adjust its size and layout to fit different screen resolutions and device types, ensuring that no part of the chatbot is cut off or hidden. The chatbot should maintain a responsive design, providing a smooth and user-friendly experience across desktops, tablets, and mobile devices.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/56ebffa4-7cab-404a-b632-34aaad65981a)
![Screenshot 2024-10-12 093959](https://github.com/user-attachments/assets/1fc58073-098f-47dd-b5bc-5658baabac30)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by rebornstar1** [comment]
actually This issue is already created

**Comment by nidhi752** [comment]
@rebornstar1 @manikumarreddyu 
no one is working on this issue.

**Comment by rebornstar1** [comment]
check issue #302

**Comment by nidhi752** [comment]
@manikumarreddyu  
this is elegently improving the ui. I am making the chatbot fit into the pages for all the devices.

**Comment by manikumarreddyu** [comment]
You can raise issue after that issue is closed...until then wait patiently... @nidhi752
