### ISSUE TITLE
[Feature Request]: Making 404 Not Found page

### ISSUE THREAD

**Issue by say-het** [manikumarreddyu/AgroTech-AI#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @manikumarreddyu.

 - I wanna make a 404 not found page.
 - when someone tries to go to some page that does not exist it should show a page 404 notfound.

I have already fixed it, can you assign me this under gssoc-ext so i can make a PR.

Little about me: I am an experienced contributor as I have successfully completed GSSoC-2024, Hacktoberfest-2020 and Hacktoberfest-2023.

### Use Case

- It stops that buggy page that shows only footer on wrong url.
- It shows proper not found page.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Complete ASAP
