### ISSUE TITLE
[Feature Request]: Farm Management System

### ISSUE THREAD

**Issue by 23wh1a0513** [manikumarreddyu/AgroTech-AI#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It helps in decision-making to boost productivity (like it tells after how hours the watering shoud be done,when they should plough them ,when to add Pesticides etc..)

### Use Case

It helps in decision-making to boost productivity (like it tells after how hours the watering shoud be done,when they should plough them ,when to add Pesticides etc..)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by 23wh1a0513** [comment]
@manikumarreddyu You have not given the level label.

**Comment by manikumarreddyu** [comment]
after seeing the work i will assign it

**Comment by 23wh1a0513** [comment]
@manikumarreddyu Here is the demo

https://github.com/user-attachments/assets/5982ecd8-e5ef-4d8f-b7c3-0221d39059ad
