### ISSUE TITLE
[Feature Request]: Rate us to backend

### ISSUE THREAD

**Issue by 17arindam** [manikumarreddyu/AgroTech-AI#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to store the rate us comment and rating in the backend which can be used to display reviews later on the website 

### Use Case

can be used to display review about the website and will help to know the review and problems from customer

### Benefits

will provide us feedback about the website and will help to improve it

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b4b8a97e-acea-4cc8-9326-96b2dc71a68c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Wait for some time...we are working on login module...after it completes you can start working
