### ISSUE TITLE
[Feature Request]: Store contact us detail in database and generating acknowledgement mail 

### ISSUE THREAD

**Issue by 17arindam** [manikumarreddyu/AgroTech-AI#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

currently the details of contact us page is not storing anywhere i want to store that in database and generate a thank you mail to the user for contacting us .

### Use Case

-it can be used to make website more interactive and will user know there message has been sent

### Benefits

can be used to contact and resolve users request

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1ad6fbf8-dad9-4522-9393-d18b580bf6db)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
See #218
