### ISSUE TITLE
[Feature Request]: dark mode toggle button not working

### ISSUE THREAD

**Issue by coderashhar** [manikumarreddyu/AgroTech-AI#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the dark mode toggle button is not working for home page . 
I would like to fix it.

### Use Case

dark mode helps reduce eye strain and provides a sleek and modern look to the website.

### Benefits

it would enhance the look and feel of the webpage

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by itznayan** [comment]
Please assign this issue to me.
