### ISSUE TITLE
[Feature Request]: Add signin with google (frontend)

### ISSUE THREAD

**Issue by NK-Works** [manikumarreddyu/AgroTech-AI#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add the signin with google features frontend where the frontend will send the 'access_token' to the backend.

### Use Case

Google login can be implemented

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
we it comes to login modules..we need frontend and backend in a single go.. i you can able to do it.. i can assign you..
tthank you @NK-Works

**Comment by NK-Works** [comment]
ok but then make it a level3 sol

**Comment by manikumarreddyu** [comment]
not needed this feature as of now..im very sorry to close the issue
