### ISSUE TITLE
[Bug]: Align Signup Page for More Attractive and Consistent Design.

### ISSUE THREAD

**Issue by NitishKumar525** [manikumarreddyu/AgroTech-AI#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Proposed Changes:
1. Proper Alignment: Adjust the positioning of the signup form, buttons, and text fields for a cleaner and more structured layout.
2. Responsive Design: Ensure that the signup page remains properly aligned on all screen sizes (desktop, tablet, mobile) to maintain visual consistency.
3. Improved Spacing: Optimize the spacing between elements like input fields, buttons, and text to give the page a balanced and polished look.
4. Enhanced Visual Appeal: Implement minor design tweaks, such as borders, shadows, or hover effects, to make the form more engaging without overwhelming the user.

### Expected behavior

Benefits:
- A well-aligned and attractive signup page will enhance the user experience and increase conversion rates.
- Improved readability and accessibility for users across all devices.
- A modern and professional design that aligns with current UI/UX standards.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5c6a7e45-b968-4704-b30c-5670d8bd068b)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Hi @NitishKumar525 it is just a single line bug... We already fixed it...it will show in deployment shortly..
Thank you @NitishKumar525
