### ISSUE TITLE
[Feature Request]: Implement User-Generated Content and Reviews Section

### ISSUE THREAD

**Issue by Varsha-1605** [manikumarreddyu/AgroTech-AI#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Description: Develop a section within the AgroTech AI platform that allows users to contribute content and provide reviews or feedback on the platform's predictions, tools, and services. This section will enable community engagement, where users can share their experiences and insights, which can help improve the platform and increase trust among users.

@manikumarreddyu Could you please assign this task to me, I would love to work on it.

### Use Case

- [ ] Users can submit reviews or comments about the accuracy and usefulness of the predictions (e.g., crop or fertilizer recommendations).
- [ ] Farmers and agricultural experts can share success stories or suggest improvements based on real-world applications.
- [ ] Users can rate the quality of the predictions, helping to refine the models over time.

### Benefits

- [ ] Builds Trust: User reviews enhance platform credibility and transparency.
- [ ] Increases Engagement: Encourages community interaction and knowledge sharing.
- [ ] Improves Platform Feedback: Offers valuable insights for refining predictions.
- [ ] Boosts User Retention: Keeps users engaged and returning.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Are you going to implement along with backend...or just you are going to develop frontend...
Please let me know @Varsha-1605 
Because...these type of modules should complete along with frontend and backend in a single go...
Thank you @Varsha-1605

**Comment by Varsha-1605** [comment]
@manikumarreddyu Yes!

@manikumarreddyu Kindly add the required labels as per the task complexity!

**Comment by Varsha-1605** [comment]
@manikumarreddyu Given the complexity and variety of features implemented,  I believe it qualifies for Level 3 rather than its current level because m not just adding a feature to a page but instead creating everything on a page from scratch.

I’d appreciate your consideration on this. Thank you!




## Screenshots
![image](https://github.com/user-attachments/assets/c173920c-6a53-44a0-8169-484ad4660766)

![image](https://github.com/user-attachments/assets/62ccc6f0-c9e3-45b2-afb4-59131089bdd6)

![image](https://github.com/user-attachments/assets/3eed5b4f-dde9-43a5-b49a-4f71071c5d58)

![image](https://github.com/user-attachments/assets/ab3a0c7f-44c9-4a48-a5c5-e6a8657817fd)

![image](https://github.com/user-attachments/assets/1ff868e4-6db2-4c56-bfde-e1699d0aadcc)

![image](https://github.com/user-attachments/assets/d4f972b3-17cf-4803-872c-ab0b10ba4e66)

![image](https://github.com/user-attachments/assets/f2359b1e-3b43-4130-8309-9b167d7c5207)

![image](https://github.com/user-attachments/assets/1b67d672-9df5-4e54-80f4-397c0abf45e5)
