### ISSUE TITLE
[Feature Request]: Implement Blog Section

### ISSUE THREAD

**Issue by Varsha-1605** [manikumarreddyu/AgroTech-AI#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Create a blog section on the AgroTech AI platform where users can read and share articles related to agriculture, farming techniques, innovations, and AI-driven solutions.

@manikumarreddyu Could you please assign this task to me, I would love to work on it.

### Use Case

- [ ] Users can access expert insights on agriculture, farming tips, and best practices.
- [ ] Admins can post articles related to updates on machine learning models, new features, and platform improvements.

### Benefits

- [ ] Knowledge Sharing: Educates users on agriculture and AI innovations.
- [ ] Engages the Community: Encourages active user participation and content creation.
- [ ] SEO Boost: Increases platform visibility through informative articles.
- [ ] Improves User Retention: Provides valuable content, encouraging users to return regularly.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Are you going to implement along with backend...or just you are going to develop frontend...
Please let me know @Varsha-1605 
Because...these type of modules should complete along with frontend and backend in a single go...
Thank you @Varsha-1605

**Comment by Varsha-1605** [comment]
@manikumarreddyu Yes!

**Comment by Varsha-1605** [comment]
@manikumarreddyu Kindly add the labels required for this task that would be helpful for me!

**Comment by Varsha-1605** [comment]
Given the complexity of the blog section, including dynamic content management, filtering, commenting, and various UI features, I believe it qualifies for higher level rather than its current level.

I’d appreciate your consideration on this. Thank you!


# Screenshots:
![image](https://github.com/user-attachments/assets/f50abf68-07e4-4e44-8552-093a433262ba)

![image](https://github.com/user-attachments/assets/0dacb352-6c2f-40d7-8cf2-2b7a1847e6d2)

![image](https://github.com/user-attachments/assets/58645850-3e8a-4d09-99d4-ee5dea9813b9)

![image](https://github.com/user-attachments/assets/3691c51c-7d40-400a-9a7b-95e572f55ac9)

![image](https://github.com/user-attachments/assets/64116d3c-76a7-4e97-8378-94bec35e9703)

![image](https://github.com/user-attachments/assets/df01965c-be8e-4348-a289-21518b32829a)
