### ISSUE TITLE
[Feature Request]: Develop RAG-based URL Analyzer for Personalized Article Insights

### ISSUE THREAD

**Issue by Varsha-1605** [manikumarreddyu/AgroTech-AI#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement a Retrieval-Augmented Generation (RAG) based URL analyzer within the AgroTech AI platform to provide users with personalized insights and summaries of agricultural articles linked from external sources.

### Use Case

- [ ] Users input URLs of agricultural articles, and the system retrieves relevant content to generate personalized summaries and insights based on the user's interests or previous interactions.
- [ ] The analyzer can highlight key points, suggest related topics, and provide actionable insights tailored to individual users.

### Benefits

- [ ] Enhanced User Experience: Provides tailored insights, making information more relevant to users.
- [ ] Increased Engagement: Encourages users to explore external content and share their findings.
- [ ] Knowledge Expansion: Offers personalized suggestions and related topics, enhancing learning.
- [ ] Efficient Information Retrieval: Saves users time by summarizing extensive articles into digestible insights.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Demo of working video... Please share me..so that I can understand this feature better.. @Varsha-1605

**Comment by Varsha-1605** [comment]
@manikumarreddyu I have screenshots of it!

## Screenshots 
![image](https://github.com/user-attachments/assets/168f3b04-359e-4a22-94d0-47bd0f0e7ed6)

![image](https://github.com/user-attachments/assets/62f13a43-6210-4518-ad4e-9b4353b4da65)

![image](https://github.com/user-attachments/assets/90808a1c-9381-490b-9fa9-3a95c4231db8)

**Comment by Varsha-1605** [comment]
@manikumarreddyu  I wanted to highlight that the task involved creating multiple components from scratch, including backend, frontend , environment management, and ensuring a secure workflow with a .gitignore file. It also includes building a URL-based QA system, document processing, Langchain integration, and various UI/UX elements for smooth navigation and user engagement.

Considering the scope and complexity, I believe this task should qualify for a higher level. I'd appreciate it if you could review and reconsider the current level assignment.

Thank you!
