### ISSUE TITLE
[Bug]: Minor bug found in the Terms and conditions section.

### ISSUE THREAD

**Issue by Jay-1409** [manikumarreddyu/AgroTech-AI#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The button does not redirect to the home page
[issues.webm](https://github.com/user-attachments/assets/f8fa3ec0-33de-4034-b8d4-cc3374944343)

### Expected behavior

The button should redirect to the home page

### On which device are you experiencing this bug?

Linux

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
complete it ASAP

**Comment by Jay-1409** [comment]
okayy!!
