### ISSUE TITLE
[Feature Request]: Recommend optimal crops based on the weather forecast.

### ISSUE THREAD

**Issue by Vaish-011** [manikumarreddyu/AgroTech-AI#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This model takes the user's location as input. It retrieves historical and forecasted weather data for that location. It predicts weather conditions such as temperature, humidity, and rainfall for the next few months or the specific time interval for which a crop grows. Based on the predicted weather, it recommends the best crop to grow.

### Use Case

The user will be able to learn about the types of crops to grow in a particular season, which will help them decide the best crop to cultivate during specific time intervals.

### Benefits

This feature add real value to project by helping farmers make smarter choices and minimize the risk of crop failure due to weather changes.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
can you do both api and fronend .. @Vaish-011 
please let me know

**Comment by Vaish-011** [comment]
yes I can do that

**Comment by manikumarreddyu** [comment]
can please share the demo video how it works . @Vaish-011
