### ISSUE TITLE
[Feature Request]: Added the privacy policy page and fixed bugs in redirection.

### ISSUE THREAD

**Issue by Jay-1409** [manikumarreddyu/AgroTech-AI#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

https://github.com/user-attachments/assets/f5a540d0-1717-4685-9e3f-a0bdfd7aa8f1

### Use Case

Privacy policy page

### Benefits

User 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
please dont do mistakes while rasing pr..
