### ISSUE TITLE
[Feature Request]: Crop Health Dashboard

### ISSUE THREAD

**Issue by aashiimathur** [manikumarreddyu/AgroTech-AI#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Crop Health Dashboard will display real-time data on crop health metrics by integrating data from satellite imagery, soil moisture sensors, and weather forecasts. Users can visualize plant growth, soil conditions, and pest alerts in one centralized interface.

### Use Case

This feature will enhance decision-making for farmers by providing a comprehensive overview of crop conditions. For example, farmers can monitor soil moisture and receive alerts for irrigation needs, leading to timely interventions.

### Benefits

Better Decision-Making: Access to integrated data enables quicker, informed decisions on irrigation and pest control.
Increased Yields: Early detection of pests and diseases can help maintain crop health.
Resource Efficiency: Insights from the dashboard promote optimal use of water, fertilizers, and pesticides, reducing costs.
Community Insights: Aggregated data analysis can benefit the agricultural community by sharing successful practices.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
we are not including iot..this feature is not needed as of now..
