### ISSUE TITLE
[Feature Request]: Improving UI for rate us box

### ISSUE THREAD

**Issue by parvkumra** [manikumarreddyu/AgroTech-AI#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This update enhances the user experience on the "Rate Us" page by implementing a visually appealing layout and introducing smooth animations. The design improvements aim to make the feedback process more engaging and intuitive for users.

Key Improvements:

Enhanced Layout: The layout has been redesigned to create a cleaner and more user-friendly interface. Elements are now better organized, ensuring users can easily navigate through the rating and feedback options.
Animated Stars: The star ratings feature now includes animations on hover, providing visual feedback as users interact with the rating system.
Placeholder Animation: The textarea for comments has an animated placeholder that grabs user attention, encouraging them to leave feedback.
Changed cancel layout

### Use Case

The user accesses the "Rate Us" page.
The user is greeted with a visually appealing layout that highlights the rating system.
The user hovers over the star ratings, which animate to provide instant visual feedback.
The user clicks on a star rating, confirming their rating choice.
The user notices an animated placeholder in the comment textarea, prompting them to write feedback.
The user types their comments and submits the feedback through a clearly labeled button.
The submission is acknowledged with a confirmation message, enhancing the overall experience.

### Add ScreenShots

https://github.com/user-attachments/assets/7dacd6b9-ca63-4b9f-b864-1e95a868e9ea

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
no iussues with current ui
