### ISSUE TITLE
[Feature Request]: I want to add redirect link from signup and signin page to home if user not want to login or signup so on click link they redirect home page

### ISSUE THREAD

**Issue by rahulbamnuya** [manikumarreddyu/AgroTech-AI#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 I want to add redirect link from signup and signin page to home if user not want to login or signup so on click link they redirect home page

### Use Case

If try to login or signup in some how they did not to do so on click link they rdirect to home page

### Add ScreenShots

![Uploading Screenshot (143).png…]()

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
not needed...
