### ISSUE TITLE
[Bug]: Incorrect Crop Names in Crop Report page and Crop Price Prediction Page

### ISSUE THREAD

**Issue by ananas304** [manikumarreddyu/AgroTech-AI#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. The crop report generated after selecting a crop from the Crop Price Prediction page displays incorrect names for most of the crops. However, the names are correct on the previous page. The crop report shows wrong names (e.g., "Wheat" is displayed as "Barley") for several crops when viewed, causing confusion for users relying on accurate data.

2. Some crop names on the Crop Price Prediction page are incorrect, leading to potential misunderstandings about the crops being referred to. Several crops, such as "Rapeseed" being labeled as "rape," are not consistently named, causing ambiguity for users. the image of copra is also incorrect.

### Expected behavior

1. the crop report to display the correct names of the selected crops, consistent with the names shown on the previous page.
2. all crop names on the Crop Price Prediction page to be accurate and consistent with standard naming conventions for crops.

### Add ScreenShots

![Screenshot 2024-10-13 171324](https://github.com/user-attachments/assets/848da409-7436-4eb5-a190-9f2a4287de0f)
![Screenshot 2024-10-13 171346](https://github.com/user-attachments/assets/f6021ebd-a852-471e-b387-b13c27694701)
![Screenshot 2024-10-13 171533](https://github.com/user-attachments/assets/67f20219-4046-4d30-af1f-6f359648a507)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ananas304** [comment]
- Please add the following tags to the issue: `gssoc`, `gssoc-ext`, `hacktoberfest`, and `hacktoberfest-accepted`.
- Kindly assign this issue to @ananas304.

Thankyou for your time :)

**Comment by manikumarreddyu** [comment]
it is just a problem from reder...you should wait 1 min...for getting rsults
