### ISSUE TITLE
[enhancement] Inconsistent Formatting and Grammar Errors in Crop Management Pages

### ISSUE THREAD

**Issue by ananas304** [manikumarreddyu/AgroTech-AI#428]
## The Crop Recommendation and Crop Rotation Recommendation pages exhibit significant inconsistencies in text formatting 
Which detracts from the overall user experience. The two pages have differing styles and layouts, making it difficult for users to navigate and absorb the information effectively. Additionally, there are several grammar mistakes present in the text, further complicating readability.

I propose to standardize the formatting across both pages to ensure a cohesive look and feel, and to thoroughly review the text for grammatical errors, enhancing clarity and professionalism. This will improve user comprehension and create a more polished appearance for the website.

---

![Screenshot 2024-10-13 171404](https://github.com/user-attachments/assets/31f6fd57-7434-4b91-85a3-c9de7bc8dcb2)
![Screenshot 2024-10-13 171425](https://github.com/user-attachments/assets/7d98a08f-2295-48ef-b76f-4b136cb5315e)

**Comment by ananas304** [comment]
- Please add the following tags to the issue: `gssoc`, `gssoc-ext`, `hacktoberfest`, and `hacktoberfest-accepted`.
- Kindly assign this issue to @ananas304.

Thankyou for your time :)

**Comment by manikumarreddyu** [comment]
not needed
