### ISSUE TITLE
[Feature Request]: ADD Password Viewer to Login and signup form

### ISSUE THREAD

**Issue by shubhagarwal1** [manikumarreddyu/AgroTech-AI#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently there is not pass view feature, i propose to add pass viewer to both login and signup form 

### Use Case

this way user can see their pass before final submission

### Benefits

more robust onboarding

### Add ScreenShots

<img width="636" alt="Screenshot 2024-1
<img width="493" alt="Screenshot 2024-10-14 at 11 03 02 AM" src="https://github.com/user-attachments/assets/8ef508ed-9b6b-4157-846e-e55e7ec4f421">
0-14 at 11 02 46 AM" src="https://github.com/user-attachments/assets/fd417ce7-6dbc-451a-9232-753fa24934cd">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by kartik3110** [comment]
please assign me this issue.

**Comment by shubhagarwal1** [comment]
> please assign me this issue.

Hey @kartik3110, great to see your spirit for contribution, but as this is GSSOC, they have their guidelines to contribute,
 according to which PR should not be raised before issue assignment, disbobyeing this can lead your Git profile to ban. 
![Screenshot 2024-10-14 at 7 46 10 PM](https://github.com/user-attachments/assets/1a2c5e38-3d9a-4e4a-b10f-ec345b484f99)
@manikumarreddyu

**Comment by manikumarreddyu** [comment]
yeah @shubhagarwal1 you are correct
