### ISSUE TITLE
[Feature Request]:Add loading and disabling login signup button to eliminate debounce also adding toaster on sign up

### ISSUE THREAD

**Issue by shubhagarwal1** [manikumarreddyu/AgroTech-AI#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add loading and disabling login signup button to eliminate debounce so that user go to know about the page is active

### Use Case

this way user will remain conneted to the things

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by shubhagarwal1** [comment]
> toaster is already there bro.. dd loading and disabling login signup button to eliminate debounce no need this as of now

@manikumarreddyu 
I understand, is there anything specific to feature addition or anything else which i can work on 
it would be a great opportunity for me

**Comment by manikumarreddyu** [comment]
loading and disabling login signup button to eliminate debounce 

actually i didnt get it.. @shubhagarwal1 can you elaborate it or explain with video..of its working in our website

**Comment by shubhagarwal1** [comment]
> loading and disabling login signup button to eliminate debounce
> 
> actually i didnt get it.. @shubhagarwal1 can you elaborate it or explain with video..of its working in our website

Sure, lets take a case where , when a user on the signup page fills the form and click on the sign up button 
the api gets called but the user is not acknowledged about it, as nothing happens on clicking on the sign up button, as if 
we disable the signup button hen api call is made will be a more better eperience for user
same goes with login.
@manikumarreddyu
