### ISSUE TITLE
[Feature Request] : Changing Hero image with Custom hero Image with floating animation.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [manikumarreddyu/AgroTech-AI#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to implement a feature that allows the hero image on the homepage to be replaced with a custom hero image that includes a subtle floating animation. This enhancement will create a more dynamic and engaging user experience by adding movement to the static elements of the page.

### Use Case

This feature would be particularly beneficial for users looking to highlight specific products or services in a more visually appealing manner. For instance, if we are promoting a new product, the custom hero image with a floating animation would draw users' attention immediately upon landing on the page. This can help convey a sense of innovation and attract more interactions from visitors.

### Benefits

1. Enhanced Visual Appeal: Adding a floating animation to the hero image will create a more dynamic interface, making the website feel modern and engaging.
2. Increased User Engagement: An animated hero image can capture users' attention, encouraging them to explore further, which may lead to increased interaction with other sections of the site.

## Before
![Before agro custom image](https://github.com/user-attachments/assets/9a286e2c-d46a-45ad-8b91-bdf5ea130c17)

## After
![Agro Custom hero image](https://github.com/user-attachments/assets/71b78dbe-d81a-458b-afa4-ed7d28bcd8e4)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
not needed bro
