### ISSUE TITLE
[Feature Request]: live stock feed calculator,pesticide application calculator,soil ph calculator,greenhouse climate control calculator

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [manikumarreddyu/AgroTech-AI#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

ive stock feed calculator,pesticide application calculator,soil ph calculator,greenhouse climate control calculator

### Use Case

ive stock feed calculator,pesticide application calculator,soil ph calculator,greenhouse climate control calculator

### Benefits

used by farmers

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
i think they are not needed..we need machine learning models only..as name suggests AgroTech AI
planning to remove existing calculators also..
