### ISSUE TITLE
[Bug]: Error Occurred While Predicting on AgroTech AI

### ISSUE THREAD

**Issue by shreyasparaj** [manikumarreddyu/AgroTech-AI#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When uploading an image for sugarcane disease recognition, the system fails to provide predictions. Instead, an error message saying "An error occurred while predicting" is shown in a popup. This issue prevents the user from obtaining any disease diagnosis for the uploaded image.

### Expected behavior

- After uploading a sugarcane plant image, the system should analyze the image and return potential disease predictions.
- If the image doesn't meet the required criteria, the user should receive a clear validation message such as: "Invalid image format" or "No disease detected."

### Add ScreenShots

![Screenshot (589)](https://github.com/user-attachments/assets/6174c0d9-b0e9-4825-8bf3-3755f1545eb4)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @shreyasparaj we havent deployed backend yet..we are already workinig on it
