### ISSUE TITLE
Customization of about us page 

### ISSUE THREAD

**Issue by azhar47-sk** [manikumarreddyu/AgroTech-AI#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The about us page is not responsive for mobile devices and the about us button in home page should redirect in about us page 

### Expected behavior

Want to update responsiveness to about us page

### On which device are you experiencing this bug?

Android

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by azhar47-sk** [comment]
please assign this issue to me .

**Comment by daud0x0** [comment]
@azhar47-sk, are you working on that bug?

**Comment by azhar47-sk** [comment]
Yess
