### ISSUE TITLE
[Feature Request]: Add Hover Effects and Animations to Navbar Logo and Nav Items

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [manikumarreddyu/AgroTech-AI#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current navbar design lacks engaging hover effects and animations. The logo does not respond to hover actions, and the nav items lack proper animations such as underline effects. This makes the navbar feel static and less interactive, which could reduce user engagement. By adding hover effects and underline animations, we can make the navbar more visually appealing and dynamic.

### Use Case

# Use Cases for Navbar Enhancements

### Use Case 1: Hover Effect on Navbar Logo
**Title**: Add hover effect to the navbar logo.

- **Actor**: Website User
- **Trigger**: User hovers over the logo.
- **Success**: Logo animates (e.g., scaling or color change), enhancing interactivity.
- **Postcondition**: User sees a dynamic logo interaction.

### Use Case 2: Underline Animation on Nav Items
**Title**: Add underline animation to navbar items.

- **Actor**: Website User
- **Trigger**: User hovers over a nav item.
- **Success**: Underline animation appears, providing visual feedback.
- **Postcondition**: Navbar feels more responsive and interactive.

### Use Case 3: Hover Effects on Nav Items
**Title**: Improve hover effects on navbar items.

- **Actor**: Website User
- **Trigger**: User hovers over a navbar item.
- **Success**: Nav items change (e.g., background or font color), improving engagement.
- **Postcondition**: User has a smoother and more intuitive navigation experience.

### Use Case 4: Overall Navbar Aesthetics
**Title**: Enhance navbar interactivity and aesthetics.

- **Actor**: Website User
- **Trigger**: User interacts with the navbar.
- **Success**: Elements respond with animations, improving user experience.
- **Postcondition**: Website becomes more polished and visually appealing.

### Benefits

# Benefits of Navbar Enhancements

### 1. Improved User Engagement
- **Interactive Effects**: Hover effects and animations on the logo and nav items make the website more engaging, encouraging users to interact with the content.
  
### 2. Enhanced User Experience
- **Visual Feedback**: Underline animations and smooth transitions provide immediate visual feedback, making navigation more intuitive and user-friendly.

### 3. Modern and Professional Design
- **Aesthetic Appeal**: Well-designed hover effects and animations give the website a polished, modern look, enhancing its overall visual appeal.

### 4. Increased Attention to Key Elements
- **Highlight Important Features**: Animating the login, cart icons, and nav items helps draw attention to important functions, improving user interaction with critical elements.

### 5. Consistency and Cohesion
- **Cohesive Design**: Adding uniform hover effects across the navbar ensures consistency, contributing to a smoother and more professional browsing experience.

### Add ScreenShots

 
![navbar6](https://github.com/user-attachments/assets/9df40dab-b76b-4a0e-ae3a-f9116f4efeb8)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Not needed
