### ISSUE TITLE
[Feature Request]: Google OAuth 2.0 for Secure User Authentication

### ISSUE THREAD

**Issue by KhawajaFashi** [manikumarreddyu/AgroTech-AI#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Summary of the Problem:
The website currently lacks Google OAuth verification, preventing users from securely signing in with their Google accounts. Implementing OAuth 2.0 will allow users to authenticate through Google, enhancing security and ease of access.

## Expected Behavior:
- OAuth Consent Screen: Create and configure a Google OAuth consent screen to allow users to review the permissions being requested.
- OAuth 2.0 Credentials: Generate and configure OAuth 2.0 credentials (Client ID, Client Secret) within the Google Cloud project for secure authentication.
- User Authentication: Implement the full Google OAuth 2.0 flow to allow users to sign in with their Google accounts.
- Token Management: Handle access tokens securely to maintain user sessions and refresh tokens as needed.
- Error Handling: Ensure the system handles errors (e.g., denied consent, token expiration) gracefully.
- Secure Data Storage: Safely store and manage sensitive credentials like Client ID and Secret.
## Current Behavior:
- There is no OAuth verification process, so users cannot log in with their Google accounts.
- No consent screen or credential management is currently implemented.
## Benefits:
- Improved Security: Google OAuth adds an additional layer of security by offloading authentication to Google’s secure infrastructure.
- Better User Experience: Users can easily sign in using their Google accounts, reducing the need to create and remember separate login credentials.
- Trust and Reliability: Users are more likely to trust a platform that supports a well-known and secure authentication method like Google OAuth.

### Screenshots

![Screenshot (424)](https://github.com/user-attachments/assets/cff8c36c-4f01-4114-a093-e5d519d45b08)

## Labels:
- Type: Enhancement
- Priority: High
- Status: Open
- Area: Authentication

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
As of now it is not needed...we will try in future
