### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by savvyjatrana2006** [manikumarreddyu/AgroTech-AI#506]
The website's color scheme may not be accessible to users with visual impairments. You could suggest adjusting the color scheme to ensure it meets accessibility standards and is more inclusive for users with disabilities.

**Comment by Meetjain1** [comment]
Hi @manikumarreddyu,  

Whenever you close an issue without assigning it, please make sure to provide a reason. This helps foster a positive environment among contributors. Without a reason, it can come across as abrupt or discourteous.

I can see #506 , #505 , #507 closed without any reasons.

Core Team 
Gssoc-extd
