### ISSUE TITLE
[BUG]: Make the website Multilingual

### ISSUE THREAD

**Issue by Swarali1107** [manikumarreddyu/AgroTech-AI#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Feature Request: We need to implement multilingual support for the Agrotech AI website to make it accessible to a wider audience, especially farmers from various regions.

### Expected behavior

Proposed Solution:

Language Files: Create JSON/YAML files for different languages (e.g., English, Hindi, etc.).

Example: en.json, hi.json, etc., containing key-value pairs for translated text.
Language Switcher: Implement a language switcher (dropdown or buttons) for users to choose their preferred language.

Dynamic Content Loading: Modify the frontend to load text dynamically based on the selected language. This could involve using JavaScript frameworks or libraries like i18next or vanilla JS.

Multilingual SEO: Ensure the URLs and metadata reflect the selected language for SEO purposes (e.g., example.com/en/, example.com/hi/).

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @Swarali1107 ..thank you so much for showing interest in this project and your idea is excellent ...can you implement it using google translate modeule....because in previous project we have have already tried your idea using i18next...for that we have faced so many problems as the project size increases...so it is better to implement that by using google translate...

take referece from this repo...
https://github.com/VaibhavArora314/StyleShare
we have shifted from  i18next to google translate...check this repo once...

please let me know if any information is needed...

**Comment by Swarali1107** [comment]
Great...I will work on it today and will report to you till evening

**Comment by Swarali1107** [comment]
@manikumarreddyu I have mailed you about the issue...kindly check my mail and reply

**Comment by Swarali1107** [comment]
Hi,

I hope you're doing well. I wanted to ask you about the Google Translate
API integration for the multilingual support feature. While the API does
offer a free tier, it requires a billing account to be set up. The free
tier allows up to 500,000 characters per month at no cost. However, if the
usage exceeds that, charges will be applied.

Could you please confirm whether you would like me to proceed with the free
version, with careful monitoring of usage, or if you’d prefer the paid
version for larger-scale usage without restrictions?
In free version I think Microsoft translator (azure) will be better ...as
it allows 2M character per month

Once I receive your confirmation, I can move forward accordingly.

Looking forward to your response.

**Comment by manikumarreddyu** [comment]
hi ,
@Swarali1107 please dont go for paid versions...try to use free versions only..if they ask you to give credit/debit card details..please dont give.i dont want to put you in risk beacuse of this task.

https://github.com/VaibhavArora314/StyleShare/blob/main/frontend/src/components/GoogleTranslate.tsx

check this once...i think they have not used any api keys..not sure..but you check it once.
thank you

**Comment by manikumarreddyu** [comment]
hey @Swarali1107   thanks you so much for showing interest in AgroTech AI..looking for more contributions from your side.

**Comment by manikumarreddyu** [comment]
hi @Swarali1107 any updates ?
