### ISSUE TITLE
[Feature Request]: Creating docker containerization for agrotech frontend and backend

### ISSUE THREAD

**Issue by J-B-Mugundh** [manikumarreddyu/AgroTech-AI#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Creating docker containerization for agrotech frontend and backend

### Use Case

To setup and run the project on other systems easily. 

### Benefits

Dockerizaization is essential to run the project on other systems easily. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by J-B-Mugundh** [comment]
This is saved for future!

**Comment by haseebzaki-07** [comment]
hey @manikumarreddyu can I take this issue?

**Comment by Shariq2003** [comment]
@manikumarreddyu sir, please assign me this issue.
