### ISSUE TITLE
[Feature Request]: Add 'Forgot Password' Option on Login Page

### ISSUE THREAD

**Issue by MohitSrivastava22** [manikumarreddyu/AgroTech-AI#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add the Forget password option in the login page so that if any user forget his/her password he/she can easily reset their password through email
![Screenshot (203)](https://github.com/user-attachments/assets/e7617c82-bf93-41f3-ad9c-e98c913378ea)

### Use Case

If any user Forget their password they can easily reset their password through email

### Add ScreenShots

![Screenshot (203)](https://github.com/user-attachments/assets/860b82d5-dfb0-4d2d-b7c8-725512317003)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
As of now it is taking dummy emails also...we have to setup OTP for verification..then we can implement this feature
