### ISSUE TITLE
[Feature Request]: I'd like to Improve "what our Users say" part .

### ISSUE THREAD

**Issue by abishek1740P** [manikumarreddyu/AgroTech-AI#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I'd Like to add the property of automatic sliding.

### Use Case

1. User Engagement: Automatically sliding testimonials or user feedback keeps the content dynamic, capturing the user's attention without requiring manual interaction.
2. Content Exposure: With auto-sliding, all testimonials are guaranteed to be displayed, ensuring that users see a variety of feedback without missing important ones.
3. Smooth User Experience: This feature enhances the flow of the website by offering continuous movement and interactivity, making the experience more visually appealing.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hey @abishek1740P automatic sliding is already implemented ..please check it once for your confirmation and let me know if that doesnt working..

**Comment by manikumarreddyu** [comment]
hey @abishek1740P can you please think about another idea..and implement it...and thanks you so much for showing interest in AgroTech AI..looking for more contributions from your side.

**Comment by abishek1740P** [comment]
@manikumarreddyu How about making the sliding stop when hovered over it. And i'd also like to add some expand trasition when hovered over

**Comment by manikumarreddyu** [comment]
> @manikumarreddyu How about making the sliding stop when hovered over it. And i'd also like to add some expand trasition when hovered over
sliding stop when hovered over it..this feature is already there i think...you can add this expand trasition when hovered over
