### ISSUE TITLE
 Simple Weather Data Preprocessing Pipeline

### ISSUE THREAD

**Issue by seemab24** [manikumarreddyu/AgroTech-AI#55]
Add a data preprocessing pipeline for weather data that handles missing values, normalizes the data, and encodes categorical features (e.g., weather conditions like sunny, rainy). This will ensure that the model is trained on clean and standardized data, improving prediction accuracy.

**Comment by seemab24** [comment]
hi @manikumarreddyu can you assign me this issue under gssoc extended 24 and hacktoberfest

**Comment by manikumarreddyu** [comment]
hi @seemab24 
as of now the weather forescast is not done using machine learnig it is normal weather app integrated into our agrotech ai.it is done using api call.

is there any other idea beacuse here we dont need ml model to predict weather conditions...
rather you can implement some other feature like giving warnings about cyclones or floods or any other diasters..in the existing forecast app. or you can implement options like seeing weather conditions for 5 days in a week and monthly,,hourly..like that

**Comment by manikumarreddyu** [comment]
hey @seemab24  thanks you so much for showing interest in AgroTech AI..looking for more contributions from your side.
