### ISSUE TITLE
[Feature Request]: Integrating labs, shops and irrigation apis

### ISSUE THREAD

**Issue by J-B-Mugundh** [manikumarreddyu/AgroTech-AI#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Integrating labs, shops and irrigation apis

### Use Case

Current integrations of apis are completely separate which causes the need to deploy each of them separately. I want to avoid this situation as it's not a good practice.

### Benefits

Integrating labs, shops and irrigation apis

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by J-B-Mugundh** [comment]
This is saved for future work!

**Comment by sharanikaa** [comment]
I would like to work on this, kindly assign me this issue.

**Comment by muskiagrwal** [comment]
i want to work on this issue .assign me this project

**Comment by Shariq2003** [comment]
@manikumarreddyu sir, please assign me this issue.
