### ISSUE TITLE
[Feature Request]: Enhanced Card Hover Effects for Aesthetic Appeal

### ISSUE THREAD

**Issue by aditiverma-21** [manikumarreddyu/AgroTech-AI#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

-Smooth Scaling: Cards scale slightly (scale(1.05)) on hover for a subtle enlargement effect.
-Transition: 0.3s ease-in-out for smooth animation.
-Shadow Elevation: Dynamic shadow (box-shadow: 0px 10px 15px rgba(0, 0, 0, 0.1)) gives a "lifted" look.
-Overlay Effect: Faded background overlay (rgba(0, 0, 0, 0.1)) enhances contrast.
-Circular overlay animation for visual emphasis.
-Text Highlight:Text color brightens or increases opacity for clarity and focus.
-Click Feedback:Slight compression (scale(1)) on click for responsive feedback.

### Use Case

Improve card interactivity with smooth hover animations and visual enhancements.

### Benefits

Increased User Engagement: Captivating visuals encourage more interaction with content.
Improved Aesthetics: Modern animations create a sleek, polished look.
Clear Visual Cues: Hover effects highlight important information, guiding user attention.
Enhanced Usability: Smooth transitions provide intuitive and responsive feedback.
Brand Differentiation: Unique hover effects elevate the website’s design, boosting its appeal.

### Add ScreenShots

Before 
![image](https://github.com/user-attachments/assets/f90d561e-5a31-471b-850a-7dfd529679c3)
After 
![image](https://github.com/user-attachments/assets/611ad55d-b21c-470f-ab8d-69e6f61c4ec0)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
not needed
