### ISSUE TITLE
[Feature Request]: Login and Signup Module using MongoDB

### ISSUE THREAD

**Issue by manikumarreddyu** [manikumarreddyu/AgroTech-AI#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I'd like to request the addition of a Login and Signup module that utilizes MongoDB for user authentication and management. This feature would include:

User Registration: Collect and store user data such as username, email, and password (hashed for security) in MongoDB.
User Login: Authenticate users by validating credentials against stored data.
Session Management: Use JWT (JSON Web Tokens) to maintain user sessions securely.
Password Encryption: Implement bcrypt or another secure hashing algorithm to protect passwords.

### Use Case

This feature will enable the project to manage user authentication securely and efficiently. Users will be able to:

Register new accounts.
Log in using their credentials.
Stay logged in with session management, improving overall user experience.

### Benefits

Improved Security: Storing user data in a structured and secure way using MongoDB, with password hashing, will protect sensitive information.
Scalability: MongoDB's flexible schema allows easy updates and future enhancements to user profiles.
User Experience: A streamlined login/signup flow with session management enhances the usability of the platform, making it more user-friendly.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjalis14** [comment]
I would like to add login and signup for authentication i would like to contribute

**Comment by manikumarreddyu** [comment]
hi @Anjalis14 any updates ?

**Comment by harish08102004** [comment]
Hey @manikumarreddyu if nobody is working on this issue I can work on this.

**Comment by manikumarreddyu** [comment]
Hi @harish08102004 you go ahead...

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @harish08102004

**Comment by harish08102004** [comment]
By today this will be done.

**Comment by J-B-Mugundh** [comment]
@manikumarreddyu will it be possible to assign me this issue if nobody had responded so far. I could also continue my work with community forum based on this.

**Comment by harish08102004** [comment]
Hey @J-B-Mugundh I'm already on it.

**Comment by J-B-Mugundh** [comment]
> Hey @J-B-Mugundh I'm already on it.
> 

Okay! Carry on.. Please try to make it a bit quick as u mentioned it would be over by yesterday.

**Comment by manikumarreddyu** [comment]
hi @harish08102004 i m very sorry to infrom you that..today evening is your deadline to complete this issue..whatever may be the reasons for not completing...it should be completed...because many other issues are in pending because of this one...please understand the situation and work according to it..it been a week already..
