### ISSUE TITLE
[Bug]: Fonts in the 'Explore our products' page are not in contrast - not legible.

### ISSUE THREAD

**Issue by omkar861856** [manikumarreddyu/AgroTech-AI#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Fonts in the 'Explore our products' page are not in contrast - not legible.

### Expected behavior

User must be able to read the fonts 

### Add ScreenShots

<img width="1391" alt="Screenshot 2024-10-20 at 11 26 35 PM" src="https://github.com/user-attachments/assets/92b32be6-1194-4675-9e97-9373c813a890">

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Can you elaborate using screenshots or videos

**Comment by omkar861856** [comment]
<img width="1391" alt="Screenshot 2024-10-20 at 11 26 35 PM" src="https://github.com/user-attachments/assets/f21b50e5-9bb3-4603-9ee8-234e56f563cb">
If you can look - because of the background image the fonts/paragraphs are overshadowed by the background image - and thats the whole point - for people to read - of a website.

**Comment by manikumarreddyu** [comment]
we have already planned to remove those bg images..it is already ongoing.

**Comment by omkar861856** [comment]
If there are any modifications to be done - please let me know - I am good
at MERN and generative AI.
