### ISSUE TITLE
[Feature Request]: Integrate Password Recovery Feature

### ISSUE THREAD

**Issue by saras-69** [manikumarreddyu/AgroTech-AI#592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Integrate the Password Recovery Feature to enable users to reset their passwords seamlessly. This enhancement involves connecting the frontend with APIs (or backend in the future) to send OTPs, verify them, and allow password reset.

### Use Case

This feature will allow users to quickly regain access to their accounts in case they forget their passwords. For example, if a user cannot log in, they can enter their email to receive an OTP, verify it, and set a new password.

### Benefits

Improves user experience by providing a recovery mechanism.
Reduces user frustration and prevents account lockouts.
Prepares the frontend for smooth integration with future backend OTP and email services.

### Add ScreenShots

![Screenshot 2024-10-20 025545](https://github.com/user-attachments/assets/410160fa-4673-4613-bdea-2a483b311877)
![Screenshot 2024-10-15 192639](https://github.com/user-attachments/assets/e39510ce-eae3-4eb9-8dd3-592de1e41363)
![Screenshot 2024-10-20 014214](https://github.com/user-attachments/assets/32eb57fd-3d65-45cf-a8c9-ddbd512aa6e5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Don't change the current ui...just add the feature

**Comment by J-B-Mugundh** [comment]
@manikumarreddyu The forget password isn't implemented properly. In case you change the mind to assign it to someone else, please assign it to me. I don't have in hand experience but i've looked on other implementations to work on this. And, i'm not sure if the current implementation matches the purpose.
