### ISSUE TITLE
[Feature Request]: Create Banners for Multiple Product Categories using canva

### ISSUE THREAD

**Issue by IkkiOcean** [manikumarreddyu/AgroTech-AI#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Description
We need to create visually appealing banners for the following product categories in our AgroShop application. Each banner should effectively represent the respective category and enhance the user experience by providing clear visual cues.

#### Product Categories
- Herbicides
- Growth Promoters
- Fungicides
- Vegetable & Fruit Seeds
- Farm Machinery
- Nutrients
- Insecticide
- Organic Farming
- Animal Husbandry
- New Products

### Use Case

- Banners grab the attention of users, making specific product categories more noticeable compared to standard text links.
- Banners can be used to promote discounts, seasonal sales, or special offers within specific categories, driving conversions.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by muskiagrwal** [comment]
i want to work on this issue .assign me this project

**Comment by IkkiOcean** [comment]
I'm in process of making these banners, only few of them are left. I will pr soon

> i want to work on this issue .assign me this project
