### ISSUE TITLE
[Feature Request]: Disaster Warnings Integration

### ISSUE THREAD

**Issue by Rucha3104** [manikumarreddyu/AgroTech-AI#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Another potential improvement is adding disaster warnings, such as alerts for cyclones or floods, into the weather forecasting feature. While the project currently includes weather data via API calls, expanding it with such warnings could significantly enhance the system’s utility for farmers

### Use Case

A farmer using the AgroTech-AI platform inputs their crop details and current weather conditions to receive crop recommendations. By integrating a disaster warning system, the platform can now analyze upcoming weather events (e.g., cyclones or floods) in the farmer's region. If any severe weather event is forecasted, the system immediately provides alerts and suggests crop protection measures or evacuation plans, giving the farmer time to prepare and mitigate potential crop loss.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ChitteshKumar** [comment]
Can I work on this issue if it is available

**Comment by manikumarreddyu** [comment]
hey @ChitteshKumar Thank you for showing interest in AgroTech AI...

you can go ahead with this issue..

**Comment by manikumarreddyu** [comment]
hi @ChitteshKumar any updates ?

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @ChitteshKumar
