### ISSUE TITLE
[Bug]: Image Not Visible and Dark Mode Position Hinders Page Flow

### ISSUE THREAD

**Issue by RabdeepKaur** [manikumarreddyu/AgroTech-AI#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Step to create :
1.click on soil fertilizer 
2. select Fertilizer Prediction
3.  the image of wheat is not visble 
4.  the dark mode hinders the flow of page and make crop gowth stage title difficult to read 

### Expected behavior

the image of the wheat should be visble 
the dark mode  icon should be present on the nav bar or some place else 

### Add ScreenShots

https://github.com/user-attachments/assets/ac587c9c-82cf-4a4d-ab6b-a621cd901179

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by BlossomBreeze25** [comment]
I want to work on this issue . can i ?

**Comment by manikumarreddyu** [comment]
already planned to remove that wheat..image and also..dark mode..
