### ISSUE TITLE
small bug in mobile view the content is out of the box 

### ISSUE THREAD

**Issue by Anjalis14** [manikumarreddyu/AgroTech-AI#612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![dessssk](https://github.com/user-attachments/assets/19c6fe4f-a966-4aca-80cd-123058fd759f)

### Use Case

after update 

![iiiijijijij](https://github.com/user-attachments/assets/84f0340c-5b5c-4d48-9f46-05fba3f7e3f3)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
we are already working on this issues related to different screen sizes....
