### ISSUE TITLE
[Feature Request]: Add realtime  crop health dashboard  in india

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [manikumarreddyu/AgroTech-AI#615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add realtime  crop health dashboard  with high medium low anamoly 

### Use Case

Add realtime  crop health dashboard  in india  low anamoly 

### Add ScreenShots

<img width="958" alt="map" src="https://github.com/user-attachments/assets/4df615f6-df4a-477e-bf04-5af762ab8f7e">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
this feature is not needed...at present..we are mainly focussing on ML models...
