### ISSUE TITLE
[Feature Request]: Rooted in Support

### ISSUE THREAD

**Issue by 23wh1a0513** [manikumarreddyu/AgroTech-AI#618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Integrating a Donor Details Section into the AgroTech AI platform will not only enhance transparency and trust among users but also serve as a valuable tool for donor recognition and engagement. By showcasing the contributions of donors and how their support drives the platform’s success, the AgroTech community can foster a collaborative environment that encourages further investment in agricultural innovation and development.

### Use Case

By having this famers can directly get contact with others and get help.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by 23wh1a0513** [comment]
@manikumarreddyu assign to me

**Comment by manikumarreddyu** [comment]
as of now..this is not needed...
