### ISSUE TITLE
[Feature Request]: Improve the UI and add rest of the CRUD features along with email sending for Irrigation Task Reminders

### ISSUE THREAD

**Issue by J-B-Mugundh** [manikumarreddyu/AgroTech-AI#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Improve the UI and add rest of the CRUD features along with email sending for Irrigation Task Reminders

### Use Case

Irrigation Task Reminders

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sharanikaa** [comment]
I would like to work on this, kindly assign me this issue.

**Comment by muskiagrwal** [comment]
i want to work on this issue .assign me this project
