### ISSUE TITLE
[Feature Request]: Creating "Add to Cart" Page to the agroshop

### ISSUE THREAD

**Issue by IkkiOcean** [manikumarreddyu/AgroTech-AI#647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to implement an "Add to Cart" page for the AgroShop application. This feature will allow users to easily add items to their shopping cart and view their selections before proceeding to checkout.

**Proposed Features for the "Add to Cart" Page:**
1. **Cart Summary:**
   - Show a summary of items added to the cart, including the quantity and total price.

2. **Quantity Adjustment:**
   - Allow users to adjust the quantity of items in their cart.

3. **Remove Items:**
   - Provide an option to remove items from the cart.

4. **Proceed to Checkout:**
   - Include a button to proceed to the checkout page.

### Use Case

- Allows users to manage their selected products easily, leading to a more intuitive shopping experience.
-  well-designed "Add to Cart" feature can lead to higher conversion rates as users are more likely to complete their purchases.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sharanikaa** [comment]
I would like to work on this, kindly assign me this issue.
