### ISSUE TITLE
Implement a Enhacing Disease Detection page | As of now it takes us to no where 

### ISSUE THREAD

**Issue by shubhagarwal1** [manikumarreddyu/AgroTech-AI#650]
<img width="1388" alt="Screenshot 2024-10-25 at 4 16 12 AM" src="https://github.com/user-attachments/assets/c891201f-27fc-4471-a433-c1c087cf3a8d">
Hey @manikumarreddyu please allow me to complete this task

**Comment by manikumarreddyu** [comment]
Hey @shubhagarwal1 
1. Please follow the issue template
2. Please check the website thoroughly 
3. Disease detection api is working fine
