### ISSUE TITLE
ADD Forecast Page | Integrating weather API

### ISSUE THREAD

**Issue by shubhagarwal1** [manikumarreddyu/AgroTech-AI#651]
<img width="1371" alt="Screenshot 2024-10-25 at 4 17 19 AM" src="https://github.com/user-attachments/assets/6e5737f5-6f85-48be-87fe-da230bcc0888">
Hey @manikumarreddyu I will be utilising weather api for the output results, please allow me to complete this task

**Comment by manikumarreddyu** [comment]
Hey @shubhagarwal1 
1. Please follow the issue template
2. Please check the website thoroughly 
Weather forecast is already there...

**Comment by shubhagarwal1** [comment]
> Hey @shubhagarwal1
> 
> 1. Please follow the issue template
> 2. Please check the website thoroughly
>    Weather forecast is already there...

hey @manikumarreddyu i understandand can i create a skeleton loading for landing page, that might enhance the user experience
