### ISSUE TITLE
 feat: Loading Skeletons to the landing page 

### ISSUE THREAD

**Issue by shubhagarwal1** [manikumarreddyu/AgroTech-AI#652]
Hey it is not specific for landing if you want i can implment that for other pages

**Comment by manikumarreddyu** [comment]
Hey @shubhagarwal1 
1. Please follow the issue template
2. Please check the website thoroughly 
As of now this feature is not needed

**Comment by shubhagarwal1** [comment]
hey @manikumarreddyu i want to work on agrotech ai, can you please tell me something you have planned to, implement and would love to work on it

**Comment by manikumarreddyu** [comment]
hi @shubhagarwal1 
connect me here : https://www.linkedin.com/in/manikumarreddyu
