### ISSUE TITLE
[Bug]: Mail Not Sending

### ISSUE THREAD

**Issue by PriyanshuValiya** [manikumarreddyu/AgroTech-AI#659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is feature is not working properly also UI is not too good.

### Expected behavior

i will improve UI and fix bugs in this feature.

### Add ScreenShots

![Screenshot 2024-10-22 210539](https://github.com/user-attachments/assets/5e0102dc-b445-4f62-8645-0f537e40c72d)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Venkateeshh** [comment]
I would like to work on this issue . can you assign this to me .

**Comment by manikumarreddyu** [comment]
which mail...
