### ISSUE TITLE
[Bug]: Login Bug

### ISSUE THREAD

**Issue by haseebzaki-07** [manikumarreddyu/AgroTech-AI#662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

user asked to login even after the user's token is stored in the localStorage. 
See the login button in the picture.

### Expected behavior

A logout button should be known if the users token is in the localStorage of the browser.

### Add ScreenShots

![Screenshot 2024-10-25 153031](https://github.com/user-attachments/assets/d5e98c7a-abcc-4dfe-9f12-e689dc176985)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
it is already resolved
