### ISSUE TITLE
Enhanced Footer with Social Links ON README

### ISSUE THREAD

**Issue by alo7lika** [manikumarreddyu/AgroTech-AI#664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This update aims to enhance the visibility and accessibility of our project's social media presence by adding a footer section in the README file that includes links to our official social media accounts. By incorporating these links, users will be able to easily connect with us on platforms like GitHub, Twitter, and LinkedIn, fostering a stronger community around our project. The enhanced footer will provide a centralized location for users to follow updates, engage with our content, and participate in discussions, ultimately improving user engagement and collaboration. This documentation update will not only promote our social channels but also encourage more active participation in the project.

### Suggested Change

I propose adding a new section to the README file that serves as a footer, incorporating links to our project's official social media accounts

### Rationale

1. Improved Engagement: Including social media links encourages users to connect with the project on various platforms, increasing engagement and fostering a sense of community.
2. Centralized Information: The footer will serve as a convenient location for users to find all relevant social links without searching through different sections of the README.
3. Promoting Updates: By linking to our social media, we can keep users informed about project updates, releases, and community events more effectively.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by alo7lika** [comment]
Assign me the task under GSSOC EXT 24 AND HACKTOBERFEST @manikumarreddyu

**Comment by manikumarreddyu** [comment]
we dont have any ssocial media accounts
