### ISSUE TITLE
[Feature Request]: Add a Government Schemes page to the website

### ISSUE THREAD

**Issue by Nelcy17** [manikumarreddyu/AgroTech-AI#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose creating a Government Schemes  page with the following features:

- Subsidies
- Grants given to Farmers
- Various schemes by the government

### Use Case

It will provide a brief description of the recent schemes, grants and subsidies.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
not a part of this project idea
