### ISSUE TITLE
[Feature Request]: Add a Visitor Counter feature ✨

### ISSUE THREAD

**Issue by Peart-Guy** [manikumarreddyu/AgroTech-AI#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a Visitor Counter feature properly.

@manikumarreddyu Please assign me the work

### Use Case

The feature would show the visitor count 

### Add ScreenShots

![Screenshot 2024-10-26 004029](https://github.com/user-attachments/assets/ded4885a-7a07-458b-8410-3781f2f63d30)
![Screenshot 2024-10-26 004024](https://github.com/user-attachments/assets/3c7d73d2-16d2-44fc-9946-80397967c8f2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @Peart-Guy please place the visitor counter in footer..at appropriate place

**Comment by sharanikaa** [comment]
I would like to work on this, kindly assign me this issue.
