### ISSUE TITLE
[Bug]: No response from this api endpoint if we go on crop recommendation model give all null values No response and Form handling issue

### ISSUE THREAD

**Issue by Raj100** [manikumarreddyu/AgroTech-AI#675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://crop-rotation-api.onrender.com/crop_recommendation this api endpoint sends no response and no form handling in frontend the form should only be submitted when the data is in correct format

### Expected behavior

-  the form should only be submitted when the data is in correct format
- Issue with Backend 

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-10-26 at 3 35 32 AM" src="https://github.com/user-attachments/assets/9da9c6aa-435e-4d7f-9ce7-479f355147f7">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
api changed
