### ISSUE TITLE
Add more description in AgroTech AI section in footer

### ISSUE THREAD

**Issue by PreetiTamana** [manikumarreddyu/AgroTech-AI#676]
Add more description in AgroTech AI section in footer to make it more informative and better understanding.

https://1drv.ms/i/c/3eafba334c127cda/ETQIhLgThnBGjx_vDDlXM2QBaai99kAi2O1bE_WyX19M4w?e=CrN7pz

thank you.

**Comment by manikumarreddyu** [comment]
not needed
