### ISSUE TITLE
[Feature Request]: About Us Page

### ISSUE THREAD

**Issue by manikumarreddyu** [manikumarreddyu/AgroTech-AI#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose the creation of an About Us page for the AgroTech platform that provides users with comprehensive information about the organization. The page will include:

Our Mission: A statement that reflects the core mission and vision of AgroTech in supporting the agricultural community.
Our Story: A brief history of how AgroTech was founded, its evolution, and its commitment to empowering farmers and promoting sustainable practices.
Our Team: Introductions to key team members, highlighting their roles, expertise, and contributions to the organization.
Partnerships: Information on partnerships with agricultural organizations, research institutions, and technology providers that enhance the platform's offerings.
Contact Information: A section providing users with ways to reach out for inquiries, feedback, or support.

### Use Case

This feature will benefit users by:

Building Trust: Providing transparent information about AgroTech’s mission and values can foster trust and credibility among users.
Creating a Connection: Sharing the organization’s story and team members can create a personal connection with the community, encouraging engagement.
Informing Users: The page will inform users about AgroTech’s partnerships and collaborations, showcasing the breadth of resources and support available.

### Benefits

Enhanced User Engagement: An informative and well-designed About Us page can improve user interaction with the platform, making it more relatable.
Strengthened Community: By sharing the organization’s values and mission, AgroTech can strengthen its community presence and encourage collaboration among users.
Increased Awareness: Highlighting partnerships and team expertise can raise awareness about AgroTech’s initiatives and the resources available to users.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anjalis14** [comment]
I would like to contribute to this.

**Comment by rebornstar1** [comment]
I would like to contribute to this issue

**Comment by manikumarreddyu** [comment]
hi @rebornstar1 can you please explore other issues also...because as per gssoc rules..who ever asks first the project admins sholud assign to them first..if the issue is not resolved for more than 5 to 7 days..then the admins can re assign the issue to the next person..i think you understand..

explore the website..come with some new ideas and i will definitely assign you...
if you find any bugs..in the current website please let me know..you can work on that..
thank you @rebornstar1

**Comment by prisha-sh** [comment]
Hey I'm interested please assign me, and I'll share my proposed solution as soon as u ping me !!

**Comment by manikumarreddyu** [comment]
hi @Anjalis14 any updates ?

**Comment by Anjalis14** [comment]
yes sir working on it @manikumarreddyu

**Comment by Anjalis14** [comment]
@manikumarreddyu  i will update it till tommoroww thanks

**Comment by manikumarreddyu** [comment]
hi @Anjalis14 i had already updated it..try to enhance the aboutus page..
use only taiwind css..make sure it is responsive to all screen sizes..

https://agro-tech-ai.vercel.app/about

https://github.com/manikumarreddyu/AgroTech-AI/blob/main/frontend/src/pages/About.jsx
