### ISSUE TITLE
[Feature Request]: Add transition to  FAQ section

### ISSUE THREAD

**Issue by haseebzaki-07** [manikumarreddyu/AgroTech-AI#680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add transition to the FAQ section to make it look visually more appealing

### Use Case

This enhances the UX of the website.

### Add ScreenShots

![Screenshot 2024-10-26 145039](https://github.com/user-attachments/assets/90dfaff2-9c97-45e1-a9fc-7390bfe27c1f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ashutoshak5386** [comment]
can you please assign this issue to me i would like to work on it.

**Comment by sharanikaa** [comment]
I would like to work on this, kindly assign me this issue.
