### ISSUE TITLE
Irrigation System Predictions not added

### ISSUE THREAD

**Issue by AswaniBolisetti** [manikumarreddyu/AgroTech-AI#686]
@manikumarreddyu 
Here irrigation system prediction page is not added 
I would like to work on it
Kindly assign it to me

https://github.com/user-attachments/assets/53544d39-9e27-4790-8e5e-4cc2145723bd

**Comment by manikumarreddyu** [comment]
so..are you going to create ML model , api and frontentend for irrigation... ?

**Comment by AswaniBolisetti** [comment]
@manikumarreddyu 
I didn't think in that way, i thought it can work using front end
I don't know about ML
