### ISSUE TITLE
Enhance Contact Us page

### ISSUE THREAD

**Issue by AswaniBolisetti** [manikumarreddyu/AgroTech-AI#699]
@manikumarreddyu 
Contact us page is not aligning with the website styling 
I would like to make it align with the website styling

Kindly assign it to me

![contact](https://github.com/user-attachments/assets/e6c93d10-f440-47c3-91cf-3483de4f2bfd)

**Comment by sharanikaa** [comment]
I would like to work on this, kindly assign me this issue.
