### ISSUE TITLE
[Feature Request]: Adding Subscribe to newsletter option in the footer

### ISSUE THREAD

**Issue by VinayLodhi1712** [manikumarreddyu/AgroTech-AI#707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding a subscribe to newsletter issue and i will do frontend and backend both part including confirmation mail to the user.

### Use Case

It will update website new features to the user with a newsletter

### Benefits

It will update website new features to the user with a newsletter

### Add ScreenShots

I will add in footer like any professional website have

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Not needed...we are in search of ml models for the website related to agriculture...

Main goal of this project is to integrate ML, DL MODELS..
