### ISSUE TITLE
[Feature Request]: adding a star us on github repo button on the beside of rate us button in footer.

### ISSUE THREAD

**Issue by VinayLodhi1712** [manikumarreddyu/AgroTech-AI#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

[Feature Request]: adding a star us on github repo button on the beside of rate us button in footer.

### Use Case

Your repo get come ahead in github.

### Add ScreenShots

![visiting](https://github.com/user-attachments/assets/03c8a927-6ec6-4ccc-a895-f3f6e5f4fd9d)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Not needed
