### ISSUE TITLE
[Feature Request]: Contact Us Page

### ISSUE THREAD

**Issue by manikumarreddyu** [manikumarreddyu/AgroTech-AI#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose the creation of a Contact Us page for the AgroTech platform that allows users to easily get in touch with the team. The page will include:

Contact Form: A simple form with fields for the user's name, email, subject, and message. Users will be able to submit inquiries, feedback, or support requests.
Email Address: A dedicated email address for inquiries that don’t require the use of the form.
Phone Number: A phone number for urgent or direct communication (optional).
Location Information: Physical office address (if applicable) with a Google Maps integration for easy location access.
Social Media Links: Links to AgroTech’s official social media profiles (e.g., Facebook, Twitter, LinkedIn, Instagram).
FAQs: A section that answers common questions, allowing users to find quick solutions to their problems without needing to contact support.

### Use Case

This feature would benefit users by:

Providing Multiple Contact Options: Users can reach AgroTech via the form, email, or phone, depending on their preference.
Encouraging Feedback: The page will make it easy for users to provide feedback, ask questions, or request support, fostering better communication.
Answering Common Queries: Including an FAQ section will help users find answers to frequent questions without needing to contact support directly.

### Benefits

Benefits:

Improved User Support: A dedicated Contact Us page will provide users with a streamlined way to reach out for assistance or information.
Better Communication: The page will enhance communication between AgroTech and its users, ensuring that inquiries and feedback are handled efficiently.
Increased User Trust: Offering multiple contact methods creates transparency and trust, showing that AgroTech is approachable and committed to its users.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ShigrafS** [comment]
I am working on this.

**Comment by manikumarreddyu** [comment]
hi @ShigrafS any updates ?

**Comment by ShigrafS** [comment]
Yeah, working on it. I was wondering whether this page needed hyperlinks to social media handles or whether a simple contact us form is enough?
