### ISSUE TITLE
[Bug]: Email & Password validation

### ISSUE THREAD

**Issue by ananyag309** [manikumarreddyu/AgroTech-AI#712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The login page has no validation check for email and password.

### Expected behavior

It should not accept emails without the type email@example.com or a similar pattern. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/646a4f63-49d3-4dde-8c6c-144063ef457a)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by haseebzaki-07** [comment]
hey @manikumarreddyu can I take this issue??
