### ISSUE TITLE
[Feature Request]: Redesign the rate up(feedback) form 

### ISSUE THREAD

**Issue by REHAN-18** [manikumarreddyu/AgroTech-AI#714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "Rate Up" or feedback form is intended to collect user impressions, suggestions, and overall satisfaction with the project. This feature request aims to redesign the feedback form to make it more visually appealing, user-friendly, and functional. It should feature a modern design, improved input fields, and intuitive navigation to encourage more users to provide feedback.

### Use Case

This redesigned feedback form will enable users to provide more detailed and meaningful insights. Users are more likely to submit feedback if the process is streamlined and engaging, helping developers to understand user sentiment, identify areas for improvement, and prioritize feature updates effectively.

### Benefits

**Improved User Experience:** A well-designed form creates a better impression and makes feedback submission enjoyable.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Venkateeshh** [comment]
im interested
