### ISSUE TITLE
[Feature Request]: Social Media Links are Missing in Footer

### ISSUE THREAD

**Issue by Suvadip-sana** [manikumarreddyu/AgroTech-AI#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I think in every standard websites has there social medial link, provided in there web platform. Which was missing in this!

I want to add some social media link with it's footer along with font awesome icons 

### Use Case

This helps user for better connectivity with you. Also scalling up this project popularity.

### Benefits

If you think it's an issue. So please assign me that issue, I want to work on it! 
and please provide me the social media links like - facebook, x, discord etc. or you can give social media links what you have.

**NOTE** I am a hacktoberfest participant. So please add this tag also.
Thank You!

### Add ScreenShots

![image](https://github.com/user-attachments/assets/032d9a30-24d6-4b44-8c5f-527318afefaf)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suvadip-sana** [comment]
Obviously. 
Could you please provide me the social media link

**Comment by manikumarreddyu** [comment]
as of now give dummy links

**Comment by Suvadip-sana** [comment]
Ok! Got it!

**Comment by Sanikaaher-19** [comment]
@manikumarreddyu  can you assign this issue to me i will do in better way and enhance user experience

**Comment by manikumarreddyu** [comment]
hi @Sanikaaher-19 first of all thanks for showing interest in this project...
as of now @Suvadip-sana is working on it..let him complete and close the issue after merging PR.
later you can raise a new issue..then i will assign you this task...i think you got my point..
thank you!

**Comment by prisha-sh** [comment]
Hey I'm interested please assign me, and I'll share my proposed solution as soon as u ping me !!
