### ISSUE TITLE
[Feature Request]: Add Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement

### ISSUE THREAD

**Issue by myselfshivams** [manikumarreddyu/AgroTech-AI#739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines

### Use Case

we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag

and have to add sitemap.xml and robots file for search engine to crawl our site.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
can i know the use of it with any demo video or any websites or any online resourses..i dont have any idea on it..
@myselfshivams

**Comment by myselfshivams** [comment]
> can i know the use of it with any demo video or any websites or any online resourses..i dont have any idea on it.. @myselfshivams

Adding meta tags, a robots.txt file, and sitemaps to a website is essential for SEO, as they help search engines understand and navigate your site more effectively. Meta tags (like title and meta descriptions) provide search engines with details about each page's content, influencing click-through rates from search results. The robots.txt file, located in your site’s root directory, tells search engines which pages to crawl or avoid, helping to manage indexing. Finally, a sitemap lists all URLs on your site, guiding search engines to important pages. For a complete guide, Moz’s SEO Essentials is a great resource.
