### ISSUE TITLE
[Bug]: Theme Toggling Text Color Mismatched | Overlapping of ChatBot and BackToTop Button on Fertilizations Prediction Page

### ISSUE THREAD

**Issue by Shariq2003** [manikumarreddyu/AgroTech-AI#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. Overlapping of ChatBot and BackToTop Button on Fertilizations Prediction Page
2. Theme Toggling Text Color Mismatched.

### Expected behavior

1. ChatBot and BackToTop buttons should not be overlapped.
2. Theme Toggling Text should always be white because its in Footer.

### Add ScreenShots

https://github.com/user-attachments/assets/1619b40f-2c00-4b84-a057-77a4c3b3c02f

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
Please remove both of them @Shariq2003 ..
Remove the code related to dark mode and remove. That msg icon behind back to top button

**Comment by Shariq2003** [comment]
> Please remove both of them @Shariq2003 .. Remove the code related to dark mode and remove. That msg icon behind back to top button

okay sir
