### ISSUE TITLE
[Enhancements]: Enhancement of Irrigation Task Reminders Page

### ISSUE THREAD

**Issue by Shariq2003** [manikumarreddyu/AgroTech-AI#748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhancement of Irrigation Task Reminders Page by fixing:-

1. Sizing of Container.
2. Marging and Paddings.
3. Background Image of the page.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9e069b79-a6c9-4d7f-b59b-1a6e26d9954f)

![image](https://github.com/user-attachments/assets/4ff976c6-098b-4a37-ab6e-28fc5bf39915)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
@Shariq2003 improve the UI of both the task reminders...they should look awesome and  the functionality should not be changed...

**Comment by Shariq2003** [comment]
> @Shariq2003 improve the UI of both the task reminders...they should look awesome and the functionality should not be changed...

okay sir
