### ISSUE TITLE
[Feature Request]: Add Theme Toggle Button or dark theme feature ✨

### ISSUE THREAD

**Issue by AnushkaChouhan25** [manikumarreddyu/AgroTech-AI#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement a theme toggle button on the website to allow users to switch between light and dark modes easily. Place the button in a prominent location, such as the top right corner, for easy access.

### Use Case

Title: Theme Toggle for Light/Dark Mode 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
it is already there in navbar.. i jst commented it...we have to do it after completion of entire website..i hope you understand @AnushkaChouhan25
