### ISSUE TITLE
[Feature Request]: Redesign and adding icons in navbar .

### ISSUE THREAD

**Issue by Sanikaaher-19** [manikumarreddyu/AgroTech-AI#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 I wanted to bring to your attention an area of improvement in our application's navbar content. Currently, I find the content to be not visually appealing and difficult to see, which might affect the user experience

I believe that by improving the navbar content and adding icons related to content it helps to the farmer community to identify it in easier way, we can enhance the overall usability and engagement of our application

### Use Case

An attractive and visible navbar will provide a better user experience, making it more enjoyable to work on the project.

### Benefits

A well-designed navbar will provide a better user experience, making it more likely for users to return to the application and recommend it to others.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Sanikaaher-19** [comment]
@manikumarreddyu  can you assign this issue to me

**Comment by rebornstar1** [comment]
@manikumarreddyu can you assign this issue to me ?

**Comment by manikumarreddyu** [comment]
hi @rebornstar1 thank ypu for showing interest in this project..
as of now @Sanikaaher-19 is currently working on this isuue...so you can check for other issues i have already mentions some issues with help wanted label..if you are intereted in any of those ..make a comment there i will assign you..i think you got my point..
thank you @rebornstar1

**Comment by prisha-sh** [comment]
Hey I'm interested please assign me, ill share my proposed solution as soon as u ping me !!

**Comment by manikumarreddyu** [comment]
hi @Sanikaaher-19 any updates ?

**Comment by manikumarreddyu** [comment]
hi @prisha-sh first of all thank you so much for your interest in this project. i have observed that you are interested in  doing many issues which are already assigned to others.

as per the gssoc rules admins are allowed to assign issue who ever asks first...if they are not showing any progress more than certain amount of time..we can assign to others..

give them some time..they are working very hard on those issues which are assigned to them..i hope you understand what i am saying.

until then you can come up with new ideas @prisha-sh 

feel free to share ideas with me,

this is my linkedin: https://www.linkedin.com/in/manikumarreddyu
