### ISSUE TITLE
[Feature Request]: Creating docker containerization for agrotech frontend and backend

### ISSUE THREAD

**Issue by Shariq2003** [manikumarreddyu/AgroTech-AI#786]
### Is there an existing issue for this?
* [x]  I have searched the existing issues
 
### Feature Description
Creating docker containerization for agrotech frontend and backend
 
### Use Case
To setup and run the project on other systems easily.
 
### Benefits
Dockerizaization is essential to run the project on other systems easily.
 
 
### Priority
High
 
### Record
* [x]  I have read the Contributing Guidelines
* [x]  I'm a GSSOC'24 contributor
* [x]  I have starred the repository

**Comment by manikumarreddyu** [comment]
it is laready completed bro ..please check repo once @Shariq2003
