### ISSUE TITLE
[Bug]: Agrotech AI Engine for Disease Detection Not Working - Issue with Model and in Image Upload Url

### ISSUE THREAD

**Issue by J-B-Mugundh** [manikumarreddyu/AgroTech-AI#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Agrotech AI engine for disease detection is failing to function correctly. Specifically, there is an issue with the image upload process. Upon attempting to upload an image for disease detection, the system does not process the image correctly, resulting in an error from the AI engine.

### Expected behavior

The image should be successfully uploaded and processed by the AI engine. The system should analyze the uploaded image and provide disease detection results promptly, as per the usual functionality.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/8eba7f7c-a964-4c84-800b-3bb6f75039bb)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by J-B-Mugundh** [comment]
@RiteshS1 Please assign me this issue. I would like to get this issue clear and get it working. Also, will add any improvements if possible. Please add gssoc-extd, hacktoberfest labels

**Comment by manikumarreddyu** [comment]
hi @J-B-Mugundh ..can you able to deploy disease-prediction-api in any free backend deployment sites..i will provide you the deep learning model file ..?
