### ISSUE TITLE
[Feature Request] E-commerce Integration for Farm Supplies

### ISSUE THREAD

**Issue by Shariq2003** [manikumarreddyu/AgroTech-AI#825]
### Is there an existing issue for this?
- [X] I have searched the existing issues

### Feature Description

To expand AgroTech AI’s functionality and provide users with direct access to essential agricultural products, we propose integrating an e-commerce store for farm supplies. This online store will enable users to purchase seeds, fertilizers, pesticides, tools, and equipment directly from the platform. Additionally, features such as product reviews and personalized recommendations will enhance user experience and assist them in making informed decisions.

### Proposed Features

1. **Product Listings**:
   - Categories for easy navigation (e.g., Seeds, Fertilizers, Pesticides, Tools, Equipment).
   - Detailed product pages with images, descriptions, specifications, and prices.

2. **Product Reviews and Ratings**:
   - Enable users to leave reviews and rate products, building trust and helping future customers make decisions.
   - Display average ratings and highlight popular or highly-rated products on the store’s main page.

**Comment by Shariq2003** [comment]
@manikdamle sir

NOTE : This issue will be complete by the 3 PRs as follows:- (i) Backend Setup for E-Commerce Store. (ii) E-commerce store page listing Products on UI. (iii) Extended Page for the Products.

**Comment by manikumarreddyu** [comment]
as of now we dont need it...we are focusing on Machine Learning models @Shariq2003

**Comment by Shariq2003** [comment]
> as of now we dont need it...we are focusing on Machine Learning models @Shariq2003

okay sir
