### ISSUE TITLE
Predicting the Optimal Harvest Time for Wine Grapes

### ISSUE THREAD

**Issue by ramana2074** [manikumarreddyu/AgroTech-AI#83]
I would like to work and develop a machine learning model that can predict the optimal harvest time for wine grapes based on historical climate data, soil type, and grape variety.

**Comment by manikumarreddyu** [comment]
hi @ramana2074 create a new api using flask for that..
1.include ipynb files in notebook folder

**Comment by manikumarreddyu** [comment]
can you please let me know how much time do you need to complete this issue @ramana2074

**Comment by ramana2074** [comment]
having a bit trouble with dataset. 2 days may be.

**Comment by manikumarreddyu** [comment]
Are you adding frontend and api...or just simply adding notebook files... @ramana2074
