### ISSUE TITLE
Add table of contents in the readme file 

### ISSUE THREAD

**Issue by T-Fathima** [manikumarreddyu/AgroTech-AI#832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I would like to add table of contents section to the readme files for easier navigation and enhance the user experience.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

@manikumarreddyu I would like to work on it.
Please assign it to me.

**Comment by Absk024** [comment]
i would like to work on it @manikumarreddyu
