### ISSUE TITLE
Add a dark mode toggle button

### ISSUE THREAD

**Issue by T-Fathima** [manikumarreddyu/AgroTech-AI#833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add dark mode toggle button for the website which enhances the user experience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Absk024** [comment]
i would like to contribute @T-Fathima

**Comment by manikumarreddyu** [comment]
it is already there in navbar.. i jst commented it...we have to do it after completion of entire website..i hope you understand @T-Fathima
