### ISSUE TITLE
[Feature Request]: Implementing Super Admin Login for DashBoard

### ISSUE THREAD

**Issue by IkkiOcean** [manikumarreddyu/AgroTech-AI#849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to implement a dedicated "Super Admin" login feature for accessing the dashboard. This feature will allow the super admin to securely log into the system and access dashboard functionalities exclusively available to their role, ensuring enhanced access control and management capabilities.

### Use Case

1. **Enhanced Security**  
   - By restricting dashboard access to super admins only, we secure sensitive data and high-level management features, reducing the risk of unauthorized access.

2. **Access Control and Role Management**  
   - Implementing a dedicated super admin login ensures clear role-based access control, allowing only super admins to access critical functions. This separation of roles provides flexibility in permissions, avoiding potential misuse by unauthorized users.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Absk024** [comment]
i would like to contribute @manikumarreddyu

**Comment by IkkiOcean** [comment]
> i would like to contribute @manikumarreddyu

Try surfing the application , you might find some issues
