### ISSUE TITLE
[Feature Request]: Improve Review Section with Stats and Feature to Upload images in Database

### ISSUE THREAD

**Issue by IkkiOcean** [manikumarreddyu/AgroTech-AI#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To improve the user experience in the review section, we need to add visual statistics and an option to upload images with reviews. This enhancement will allow users to get a quick overview of review patterns and provide more detailed feedback by attaching images. The changes will make the review section more informative and engaging for users.

### Example

<img width="1280" alt="Screenshot 2024-11-07 at 7 37 42 PM" src="https://github.com/user-attachments/assets/968d1b05-5e8c-475c-a99f-6a6b2fb9e19f">

### Use Case

1. **Enhanced User Engagement**: Allowing image uploads with reviews adds visual context, making feedback more relatable and engaging for other users.

2. **Improved Insight**: Review statistics provide quick insights into product or service performance, helping both users and admins make informed decisions.

3. **Better User Trust**: The ability to upload images builds credibility, allowing users to see real-world examples and fostering trust in reviews.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
donot create uploading pictures option as of now..just comment that part in code... @IkkiOcean
