### ISSUE TITLE
AI supported chatbot for agrotech

### ISSUE THREAD

**Issue by Sawan-Kushwah** [manikumarreddyu/AgroTech-AI#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

this is will answer user querry 
suggest good plantation method 
help farmer 

### Use Case

this whole chatbot is trained on our website data
and answer by his own intelligence

### Benefits

sample chatbot 

https://github.com/user-attachments/assets/964d5ffd-607f-4932-adb4-b28b69e1adec

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by mehul-m-prajapati** [comment]
Thanks for your valuable contubutions of chatbot everywhere. You will awarded with a new badge 🤡 
https://github.com/Jaishree2310/GlassyUI-Components/pull/432
https://github.com/anuj123upadhyay/MegaBlog/pull/391
https://github.com/Sanskriti1102/Techtalksintelligenz/pull/105
https://github.com/ANSHIKA-26/WordWise/pull/1547
https://github.com/Open-Code-Crafters/FitFlex/pull/313
https://github.com/anuj123upadhyay/MegaBlog/pull/198
https://github.com/Bitbox-Connect/Bitbox/pull/254
https://github.com/Yashgabani845/hiring-portal/pull/139

**Comment by Ajay-Berwal** [comment]
### Your tireless forum contributions have truly made a difference... so, as a token of appreciation, here's a special honor: 🎭 Take a bow, you've earned it! 

https://github.com/Yashgabani845/hiring-portal/pull/363
https://github.com/Bitbox-Connect/Bitbox/pull/433
https://github.com/Bitbox-Connect/Bitbox/pull/432
https://github.com/anuj123upadhyay/MegaBlog/pull/408  
https://github.com/anuj123upadhyay/MegaBlog/pull/407
https://github.com/Yashgabani845/hiring-portal/pull/340
https://github.com/ANSHIKA-26/WordWise/pull/1782
https://github.com/manikumarreddyu/AgroTech-AI/pull/897
https://github.com/anuj123upadhyay/MegaBlog/pull/407

@mehul-m-prajapati

**Comment by mehul-m-prajapati** [comment]
@Ajay-Berwal  - leave it bro.. this is a very low quality program. I won't participate again

**Comment by Sawan-Kushwah** [comment]
@Ajay-Berwal @mehul-m-prajapati
If a company makes a similar kind of product, it doesn't mean they are doing redundant work; they are doing so because of consumer demand. Similarly, I provide a quality product that they need. It's all about demand and supply—if they don't need it, then why would I provide it?

**Comment by mehul-m-prajapati** [comment]
@Sawan-Kushwah : Good luck making bots for other companies
