### ISSUE TITLE
The footer is not better 

### ISSUE THREAD

**Issue by jayanththalla** [manikumarreddyu/AgroTech-AI#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Improve the footer is not good

### Use Case

It is beneficial by client see the hover effects and other

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a31cbe07-a3d8-4b32-8e11-bca85fa438f9)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by anothercoder-nik** [comment]
I hope you're doing well! I wanted to reach out and see if I could contribute to this project. I noticed the footer section could use some improvement, and I'd love to take that on if possible. Could you assign me to work on this? I'd be excited to help enhance the design and make it more functional. Looking forward to your thoughts! I am an gssoc-ext 2024 contributor.

My thought process works like : 
1)We will add react-icons and some additional related icons in footer section to make it look good
2)We will going to some important animations like hover effects and extras in footer to end the user with a lead.
3)The foremost goal to make the user easily reachable the all the services that are necessary .

**Comment by manikumarreddyu** [comment]
hi @anothercoder-nik as of now @jayanththalla  is working on it..once this issue is closed you can raise another issue with all the features which you have mentioned..be patient

come with any new ideas for the project..feel free to share your thoughts..and look for any other issues in the agrotech ai
thank you @anothercoder-nik

**Comment by manikumarreddyu** [comment]
hi @anothercoder-nik 
please create a new issue now... @jayanththalla completed this issue..
