### ISSUE TITLE
[Bug]: HTTP 500 during signup when SMTP Email or Pass is incorrect (Not proper toaster message is notified)

### ISSUE THREAD

**Issue by mehul-m-prajapati** [manikumarreddyu/AgroTech-AI#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

HTTP 500 during signup when SMTP Email or Pass is incorrect (Not proper toaster message is notified)

> 

### Expected behavior

Proper toaster message stating exact reason of signup failure

### Add ScreenShots

![d1](https://github.com/user-attachments/assets/a0aa989e-bd5b-4040-b928-57939a096381)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @mehul-m-prajapati i am personally working on login module...i will do it..i hope you understand
