### ISSUE TITLE
[Bug]: Google oauth signin issue

### ISSUE THREAD

**Issue by nagaumamahesh** [manikumarreddyu/AgroTech-AI#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While Signing in with Google, there is an issue . "You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.".

API endpoint : https://agro-tech-ai.vercel.app/login

### Expected behavior

Able to login to the application using google account.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/141adfef-90b5-42dc-a6a5-18be5cb89723)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hi @nagaumamahesh it is problem from my side..while createting client id and secret key..it is not in your hands ..i will do it whenever i get free..no issues with code.i hope you understand
